### ISSUE TITLE
zeRGBa in merge mode strange behavior

### ISSUE THREAD

**Issue by gablau** [blynkkk/blynk-server#1033]
From [node-red client library](https://github.com/gablau/node-red-contrib-blynk-ws)
I realized that if I send the string value "aaaaaaaa" to the pin of the zergba in merge mode and then do a sync of that pin the server return the value I sent "aaaaaaaa", while on the app I see set 0 0 0 value.
No error message on wrong value? possible server bug?

Example protocol comunication zergba on virtual pin V0:
```
SEND -> Cmd: HW, Id: 5, len: 20, data: "vw|0|aaaaaaaaaaaaaaa"

SEND -> Cmd: HW_SYNC, Id: 6, len: 4, data: "vr|0"
RECV <- Cmd: HW, Id: 6, len: 20, data: "vw|0|aaaaaaaaaaaaaaa"

SEND -> Cmd: HW, Id: 7, len: 12, data: "vw|0|255|0|0"

SEND -> Cmd: HW_SYNC, Id: 8, len: 4, data: "vr|0"
RECV <- Cmd: HW, Id: 8, len: 12, data: "vw|0|255|0|0"
```

Best regards
Gabriele

**Comment by doom369** [comment]
@gablau this is done due to performance reasons. We do not validate values when they come to the server. Validation is done on the app side. So this is expected.
