### ISSUE TITLE
HTTP RESTful API - Local Server

### ISSUE THREAD

**Issue by dtsrwnis** [blynkkk/blynk-server#113]
With the version "server-0.12.4.jar" my c# app worked perfect now i have no response - delays and i get many times on  "Read pin value" call --> [""]  without 0 or 1 !

I run the server on raspberry as before!

**Comment by doom369** [comment]
Do you see some errors in logs? Do you use 0.12.6 at the moment?

**Comment by dtsrwnis** [comment]
Update: IOS applications is the reason!! All works smooth from android + desktop and then ... When i login from ios application and run something BOOM! --> The desktop client stop working! Very very weird!!!

**Comment by doom369** [comment]
Ok. Thank you for reporting. We will have a look.

**Comment by doom369** [comment]
When you say desktop client stop working what do you mean exactly? Also could you please have a look in logs? "logs/users/your_login_name" and "logs/blynk.log"

**Comment by dtsrwnis** [comment]
I haven't get any errors on the logs!   I mean is not do that expected to do and turn on/off the pin!

Now after that "BOOM" i click on the app to "on" the state goes to 1  but the led its not open!! CRAZY!!

Some how the API is confused!

**Comment by doom369** [comment]
Could you please make a video of issue? Would be very helpful.

**Comment by dtsrwnis** [comment]
Where you want to upload it ?

**Comment by doom369** [comment]
Dropbox maybe? Google docs? Whatever you using, just give me a link =).

**Comment by dtsrwnis** [comment]
Here is it : https://dl.dropboxusercontent.com/u/33796328/Video/20160218_002650.mp4

Hope to help!

**Comment by dtsrwnis** [comment]
Look and this :  http://i.imgur.com/wi9TsSn.png

**Comment by doom369** [comment]
Hm, thank you! Video make it clear. I think problem is pretty simple, it is - pins names. Let me check.

**Comment by doom369** [comment]
@dtsrwnis could you please post here also project json?

`http://ip/auth_token/project`

**Comment by dtsrwnis** [comment]
Yes correct! And yes the client uses REST API! 

Where i can find the project json ?

**Comment by doom369** [comment]
It is part of REST API. Just use link above with your host and token.

**Comment by dtsrwnis** [comment]
{"id":1,"name":"Esp220v","createdAt":1453704352738,"updatedAt":1455919584226,"widgets":[{"type":"BUTTON","id":1,"x":0,"y":0,"color":616861439,"width":2,"height":2,"label":"Relay","pinType":"DIGITAL","pin":13,"pwmMode":true,"rangeMappingOn":false,"min":0,"max":0,"value":"1","pushMode":false}],"boardType":"ESP8266","keepScreenOn":false,"isShared":false,"isActive":true}

**Comment by doom369** [comment]
Hm... I don't know. Just test this scenario - all is fine. Are you sure you are using 0.12.6 and latest Blynk app?

**Comment by dtsrwnis** [comment]
You have see the video proof... You test it with windows app ?   
Ios + Android works but when i call the API from c# the gpio opened in api but not in esp8266!

**Comment by dtsrwnis** [comment]
http://i.imgur.com/vyvuido.png

But the relay is not opening + I have instant on-off blink with no reason after 10-20 secs ... !!!

**Comment by doom369** [comment]
@dtsrwnis please do next :
- stop server;
- delete all logs;
- turn on "trace" log level in "server.properties";
- reproduce scenario;
- provide me with log output when HTTP API is not working;

**Comment by doom369** [comment]
@dtsrwnis one more idea - could you execute PUT request not from your program but from browser for instance with help of some REST plugin?

**Comment by dtsrwnis** [comment]
Here is the PUT Request: http://i.imgur.com/vercTeQ.png

**Comment by doom369** [comment]
@dtsrwnis I found problem. Your button is in PWM mode. This is a bug. We will fix it.

Temp solution :
- Login in Android;
- Remove button;
- Add button;

Now it should work.

**Comment by dtsrwnis** [comment]
Yeeees!!! Finally :D :D

The Temp Solution Works!

We found a bug here :D 

Nice work!

**Comment by doom369** [comment]
@dtsrwnis Thank you for your patience. This bug was tricky. I also fixed it on server side. Soon I'll do new release. (it will be faster than wait for iOS fix).
