### ISSUE TITLE
HW info message should not mix blynk and firmware versions

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-server#1137]
We should switch to some stable info scheme, so `ver` always indicates blynk ver, and an additional, optional field `fw` that indicates firmware version.

**Comment by doom369** [comment]
@vshymanskyy done. please add it after "ver" param

**Comment by vshymanskyy** [comment]
This actually may be impossible/hard to do. Please do not rely on the
sequence.
