### ISSUE TITLE
Unable to clone a project using QR-code

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#1147]
Android and iOS

**Comment by doom369** [comment]
@Refenz Steps? App version

**Comment by Refenz** [comment]
@doom369 
1. Open Blynk app
2. Click on QR-scan icon
3. Scan:
![image](https://user-images.githubusercontent.com/16590099/41822924-cc2f6ef2-77ff-11e8-9465-98d4bdb9c76e.png)

AR:
Nothing happens

**Comment by doom369** [comment]
@Refenz moved to Andorid repo
