### ISSUE TITLE
unable to run server on Mac

### ISSUE THREAD

**Issue by hamzam999** [blynkkk/blynk-server#1148]
WARNING : '' does not exists. Please specify correct -dataFolder parameter.
Your data may be lost during server restart. Using temp folder : /var/folders/cq/dd4j29h561j2kl9_wp70kjgm0000gn/T/blynk
Server ports are busy. Most probably server already launched. See /Users/muntaha/Downloads/blynkserver/./logs for more info.

![screen shot 2018-06-24 at 12 36 54 am](https://user-images.githubusercontent.com/40526398/41812767-c78a8daa-7746-11e8-98b8-e982338fb809.png)

**Comment by doom369** [comment]
@hamzam999 message is pretty clear 

> Server ports are busy. Most probably server already launched. 

Server ports are busy. Check what hold 8080 port
