### ISSUE TITLE
how to run blynk local server and homebridge simultaneoulsy on a mac or raspberry pi?

### ISSUE THREAD

**Issue by hamzam999** [blynkkk/blynk-server#1157]
once hombridge or local server is started then nothing else could be done in the terminal until I stop it by ctrl+c.
Suggest me a way please.

**Comment by doom369** [comment]
Please create the ticket within the homebridge repository.

**Comment by doom369** [comment]
@hamzam999 here is ready integration - https://github.com/ilcato/homebridge-blynk
