### ISSUE TITLE
cannot integrate home bridge and blynk, unable to control device via homebridge

### ISSUE THREAD

**Issue by hamzam999** [blynkkk/blynk-server#1158]
![screen shot 2018-06-26 at 4 37 32 am](https://user-images.githubusercontent.com/40526398/41969574-7d663c60-7a25-11e8-924e-937d5955038c.png)

![screen shot 2018-06-27 at 4 20 44 pm](https://user-images.githubusercontent.com/40526398/41969764-1b557aa8-7a26-11e8-9368-1baf0262e7f4.png)
"accessories cannot be loaded"

![screen shot 2018-06-26 at 4 41 37 am](https://user-images.githubusercontent.com/40526398/41969575-7dd16602-7a25-11e8-8782-468163305536.png)

"As you can see the value of switches does not remain constant when I turn it on homekit app on iPhone and also I cannot control my wifi switch.
the wifi switch is working fine with blynk app using both cloud and local server.''

**Comment by doom369** [comment]
Please create the ticket within the homebridge repository.
