### ISSUE TITLE
Display a stub or remove a link from reset pasword email

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#1170]
![image](https://user-images.githubusercontent.com/16590099/42354357-f5fd546a-80ce-11e8-9b7f-955b423a2025.png)

AR:
Page not found
link: http://blynk-cloud.com/restore?token=242b4a9d8407475f9991c0f48d2801d6&email=aka.roman.kirichenko@gmail.com

**Comment by doom369** [comment]
Only deployed on QA at the moment.
