### ISSUE TITLE
why after every server update the raspbian will fail ?

### ISSUE THREAD

**Issue by ErfanDL** [blynkkk/blynk-server#1171]
when I update new server the raspbian OS ( latest version ) crashed !!! and must be installed again. :|

**Comment by doom369** [comment]
What exactly must be installed again? What make you think the issue is in Blynk server?

**Comment by ErfanDL** [comment]
@doom369 the raspbian OS must be installing again. I just replacing new server java with older jar then rebooting raspberry pi and everything is crashed !

**Comment by doom369** [comment]
Provided info doesn't allow to make a conclusion that issue is because of Blynk. It could be anything.

**Comment by thatguyza** [comment]
Do you follow the upgrade instructions that are outlined [here](https://github.com/blynkkk/blynk-server)?

I've been running the local server on Raspbian for more than a year and have never had this problem.
