### ISSUE TITLE
Make CSV structure more usable to import into external editors like Excel, Numbers, etc

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-server#1174]
For PER DEVICE report:

"DeviceName 1"
"Date and Time", "Datastream 1 Name", "Datastream 2 Name", ... "Datastream N Name"
value, value, value, value, value

"DeviceName 2"
"Date and Time", "Datastream 1 Name", "Datastream 2 Name", ... "Datastream N Name"
value, value, value, value, value

...

"DeviceName N"
"Date and Time", "Datastream 1 Name", "Datastream 2 Name", ... "Datastream N Name"
value, value, value, value, value

**Comment by doom369** [comment]
What is the motivation? Current structure is requested by the client.
