### ISSUE TITLE
Raw VirtualPin Websocket API

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-server#1188]
I faced need in such functionality multiple times.
Examples:
- In-band OTA
- Listening pin updates
- Remote terminal implementation

The main idea is to have a binary websocket endpoint, that send and receives raw data of a VPin, like:
```
wss://blynk-cloud.com/auth_token/stream/V0
```

**Comment by doom369** [comment]
It is already there, both, hardware and app side. But you have to implement Blynk commands parser for it on the client side or you may use my client, however, it is not very suitable for usage right now.

Checkout WebSocketTest test.

**Comment by vshymanskyy** [comment]
Protocol is not a problem. The problem is, when hardware sends data to virtual pin, this client should also receive it.

**Comment by doom369** [comment]
I see, you need an app side client in that case.

**Comment by vshymanskyy** [comment]
App side client also has a different protocol, which I think would be overhead to support in so many instances of possible clients.
`wss://blynk-cloud.com/auth_token/stream/V0` approach instead requires only simple websocket operations, no protocol implementation (except splitting '\0' by client, if needed)
