### ISSUE TITLE
java will be killed after run several hours on Centos

### ISSUE THREAD

**Issue by hznupeter** [blynkkk/blynk-server#1207]
server version:0.39.1-java8
server:centos 7.4,RAM 1G,CPU:Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
I found that the server will be killed after several hours . I tried many times, the same results.

**Comment by doom369** [comment]
Killed by what?

**Comment by hznupeter** [comment]
can't find any log files .
Let me google first.

**Comment by doom369** [comment]
Please reopen if you have more info to look into.
