### ISSUE TITLE
static-override won't work when the Server auto started

### ISSUE THREAD

**Issue by hznupeter** [blynkkk/blynk-server#1211]
I set the blynk-server.jar auto start by modify  /etc/rc.local . It will work ,but the static-override will be ingore.
If I start the blynk-server.jar  through PuTTY, the static will be rewrite by static-override.
So ,what's the difference with the two ways?

**Comment by doom369** [comment]
Probably different relative paths.

**Comment by doom369** [comment]
closing this for now as we don't use it in production. If you'll find something please send PR.
