### ISSUE TITLE
Server stops caused by "Out of Memory" in 0.39.4

### ISSUE THREAD

**Issue by filou01** [blynkkk/blynk-server#1227]
Since my update yesterday from server-0.36.4-java8.jar to server-0.39.4-java8.jar the server stops after some hours (i guess there is a memory leak).

Following messages occur in /var/log/messages

Aug  1 03:11:38 test1 kernel: Out of memory: Kill process 497 (java) score 319 or sacrifice child
Aug  1 03:11:38 test1 kernel: Killed process 497 (java) total-vm:2296704kB, anon-rss:191928kB, file-rss:0kB, shmem-rss:0kB

If you need further debugs or anything else please instruct me how to create them.

Regards,
Christoph

**Comment by doom369** [comment]
@filou01 hello. thanks for reporting. How many RAM do you have in your env? Do you use DB?

Please run after few hours of server work (when you see large memory consumption)

`jmap -dump:format=b,file=heap.bin <java_pid>`

**Comment by filou01** [comment]
Hi Dmitriy,
i have a total of 588MByte in my server (GCP Free Instance) and i don´t use DB.
There is nothing relevant in the blynk.log file at the time of the crash (just the last login of the Device, because the devices wake from sleep every 10 minutes).
Can i downgrade to 0.39.2 without data loss?

Regards, Christoph

**Comment by doom369** [comment]
I think yes

**Comment by filou01** [comment]
Hi,

the following commands didnt work:

-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/tmp"
I downgraded to 0.39.2 but this version also crashes after certain hours. 
Any idea?
Regards, Christoph

Von meinem iPhone gesendet

**Comment by doom369** [comment]
Please try downgrade to 0.39.2.

**Comment by filou01** [comment]
0.39.2 also crashes

**Comment by filou01** [comment]
Since upgrading from OpenJRE to Oracle JRE and from Java Version 8 to 10 the system is stable with no more crashes in 0.39.4. 

Regards, Christoph

**Comment by doom369** [comment]
Should be fixed with 0.39.5
