### ISSUE TITLE
Create 500 QR codes with 10,000 Energy

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-server#1231]
Need generic codes for refunds/returns, etc.

Text:
Thanks for choosing Blynk! /n
Here is a 10,000 Energy for your amazing projects

Happy Blynking!

![img_8e5ac2fe3941-1](https://user-images.githubusercontent.com/11541426/44101679-f5e032da-9fb5-11e8-86fa-e8cea015ce49.jpeg)

**Comment by doom369** [comment]
@blynkkk sent via email
