### ISSUE TITLE
Report. Strange characters in the report

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#1247]
![image](https://user-images.githubusercontent.com/16590099/45383615-6aab1c00-b614-11e8-9dd6-97e893c21f7e.png)

Report: [SF_89046.zip](https://github.com/blynkkk/blynk-server/files/2372495/SF_89046.zip)

**Comment by doom369** [comment]
@Refenz what server?

**Comment by Refenz** [comment]
@doom369 
QA

**Comment by doom369** [comment]
@Refenz this is excel bug, it can't detect encoding correctly. When you import data you should specify encoding - UTF-16.
