### ISSUE TITLE
Preserve widget values on update

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#1266]
https://community.blynk.cc/t/widget-values-reset-to-null-when-editing-to-configuration-of-widgets-existing-and-new-of-tiles/29326

Entry handler: `MobileUpdateWidgetLogic.java`
Test example that could be reused: `WidgetWorkflowTest.java`

When `MobileUpdateWidgetLogic` handler is invoked it overrides the value of the existing widget with new copy object that comes to the handler.
Fix should preserve existing widget value with `Widget.updateValue(Widget oldWidget);`

**Comment by blynkkk** [comment]
No points in implementing this. Re-configuration = erase value(s). 
It's easy, simple, and clearly understood.

**Comment by teejaydub** [comment]
It's easy, simple, clear - and always exactly wrong in my experience, as well as surprising. Not a deal breaker for me because I already forked the server to work around it, but I'll just say it was well worth making that effort.
