### ISSUE TITLE
Cloned project leaks data

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-server#1271]
For example, when I clone the project that I shared here: https://www.hackster.io/vshymanskyy/android-ios-app-to-access-your-openwrt-router-remotely-6c23c2
It shows my IP address in Labeled Value widget (and some other widgets). Which is not good - it leaks my sensitive data.

**Comment by doom369** [comment]
@vshymanskyy sure, we can't track what users put within widgets.

**Comment by vshymanskyy** [comment]
I did not put this data. It's virtual pin value

**Comment by doom369** [comment]
@vshymanskyy and how it appears in that virtual pin?

**Comment by vshymanskyy** [comment]
Again. This is cloned PROJECT. It should not leak DATA.
