### ISSUE TITLE
Java 11 compatibility

### ISSUE THREAD

**Issue by 6wheels** [blynkkk/blynk-server#1290]
Hi,

This is not an issue but a question.
The readme indicates a compatibility with java 8 and 10.
What about java 11?

I'm currently writing a pkgbuild for properly installing blynk-server on Archlinux.
That would help me to deal with needed dependencies.

Thanks.

**Comment by doom369** [comment]
> What about java 11?

Hello, it is fully supported at the moment in the latest server version. All known issues were fixed recently.

**Comment by 6wheels** [comment]
That's great to hear!
Thanks for your super fast answer and your contributions on this great project.
Cheers.
