### ISSUE TITLE
syncVirtual() not working on 2nd device, works on 1st

### ISSUE THREAD

**Issue by hostmit** [blynkkk/blynk-server#1291]
Hello! I running my server and  have following in my loop

Blynk.syncVirtual(110); 

and following function to catch writes from "value widget"
BLYNK_WRITE(110) {
   Serial.Println("here");
}

That code works perfect on one ESP32 and doesnt trigger BLYNK_WRITE(110) on another ESP32, same server. How do I debug? Sketches are identical, auth tokens different.

**Comment by doom369** [comment]
Hello. What server version do you have?

**Comment by hostmit** [comment]
Blynk Server 0.39.12 successfully started.

**Comment by doom369** [comment]
@hostmit what widget are on v110?

**Comment by hostmit** [comment]
Value display

**Comment by doom369** [comment]
@hostmit do you use tags, device selector, tiles? How do you assign 2 devices to the smae widget?

**Comment by hostmit** [comment]
two separate projects, two devices devices

**Comment by doom369** [comment]
Please check both projects are in "Run" mode and both widgets have value.

**Comment by hostmit** [comment]
good to know :) I would add a few words description to syncvirtual() description, warning users it wont work unless value exist.
The idea of my design is following:
BLYNK_WRITE(110) {
    
    String value = param.asString();
    if (value != Alarm::blynkLastMessage)
        Blynk.virtualWrite(BLYNKALARMLASTTRIGGERVPIN, Alarm::blynkLastMessage);
}

That way I implement guaranteed delivery.
