### ISSUE TITLE
Can't set image gallery urls

### ISSUE THREAD

**Issue by bestpika** [blynkkk/blynk-server#1302]
I try to use `http://addr:port/auth/update/pin?urls=...` to set image gallery, then I get `No widget for SetWidgetProperty command.`

Blynk server: `0.41.3-SNAPSHOT`

**Comment by bestpika** [comment]
I tested and find the problem.
If I use the selector, then the image widget will can't set the property.

**Comment by doom369** [comment]
@bestpika nope. This case is not supported and we don't plan to make it work as we focused right now on the new version of Blynk.
