### ISSUE TITLE
Blynk not showing push notification.

### ISSUE THREAD

**Issue by ohharsad** [blynkkk/blynk-server#1304]
Hi

Iam running Blynk local server, it seem my blynk at android emulator (MEMU) not receiving any notification including hardware disconnected. All of the gauge run normally except notification.

i already put blynk.notify in my code, still no notification received, the notification widget already set to high priority. As you can see the below picture, the server is receiving the push notification.

My hardware information:
Ubuntu Server 18.04
Blynk server-0.41.2-java8.jar
Arduino Mega

Startup argument:
java -jar /home/sysadmin/blynkserver/blynk0.41.2.jar -dataFolder /home/sysadmin/blynkserver/datafile 

![blynk](https://user-images.githubusercontent.com/20744213/52268102-9b9a3d80-2975-11e9-8896-2527348dcc55.JPG)

Blynk Log:

sysadmin@sdg-blynk01:~/blynkserver$ cat logs/blynk.log 
10:49:09.632 INFO - Using data dir '/home/sysadmin/blynkserver/datafile'
10:49:10.291 INFO - Region : local. Host : 10.36.134.135.
10:49:10.332 INFO - Using native epoll transport.
10:49:10.870 INFO - Initializing gmail smtp mail transport. Username : example@gmail.com. SMTP host : smtp.gmail.com:587
10:49:10.905 INFO - Reports : 0
10:49:10.906 INFO - Didn't find custom user certificates.
10:49:10.908 INFO - Didn't find Let's Encrypt certificates.
10:49:10.908 WARN - You didn't specified 'server.host' or 'contact.email' properties in server.properties file. Automatic certificate generation is turned off. Please specify above properties for automatic certificates retrieval.
10:49:10.908 INFO - Using native openSSL provider.
10:49:10.933 WARN - ATTENTION. Server certificate paths (cert : '/home/sysadmin/blynkserver', key : '/home/sysadmin/blynkserver') not valid. Using embedded server certs and one way ssl. This is not secure. Please replace it with your own certs.
10:49:11.381 INFO - HTTP API and WebSockets server listening at 8080 port.
10:49:11.383 INFO - HTTPS API, WebSockets and Admin page server listening at 9443 port.
10:49:11.384 INFO - Mqtt hardware server listening at 8440 port.
10:49:13.435 INFO - admin@blynk.cc hardware joined.
10:49:13.635 INFO - admin@blynk.cc Blynk-app (android-22700) joined.

**Comment by doom369** [comment]
Do you have google play services on your emulator?

**Comment by ohharsad** [comment]
@doom369 yes it have google play service.

![image](https://user-images.githubusercontent.com/20744213/52269980-8c69be80-297a-11e9-8fa9-e58f870dcc5e.png)

**Comment by ohharsad** [comment]
Solved, it caused by the internet of the emulator. It have network but didn't have internet.
i reconfigure the network and boom lots of notification. Thanks :)
