### ISSUE TITLE
Offline message is not received

### ISSUE THREAD

**Issue by eepetrash** [blynkkk/blynk-server#1305]
1. Have a project with a Notification widget
2. In Notification widget set "Notify when Offline" to ON
3. In project settings make sure "Do not show offline" is OFF

AR: Device offline message (71) is not received
ER:  _Device offline message_ (71) is received regardless Notification widget settings. 
Related: https://github.com/blynkkk/blynk-server/issues/1232

**Comment by eepetrash** [comment]
AR: Device offline message (71) is received after `notifyWhenOfflineIgnorePeriod` from Notification widget settings
ER: Device offline message (71) is received regardless Notification widget settings.
Related: https://github.com/blynkkk/blynk-ios/issues/1835

**Comment by doom369** [comment]
@eepetrash I did a fix for and deployed, however I don't think this is how it should work.
