### ISSUE TITLE
Enable raw data storage then profile auto backup stop

### ISSUE THREAD

**Issue by bestpika** [blynkkk/blynk-server#1306]
I enabled raw data storage, then I found profile auto backup stoped.
(`/data/backup` no new file)

I found I enable raw data storage at 01/24.
Today, after reboot I got some error.

```
20:40:08.184 ERROR- Error parsing file '/opt/blynk/data/....Blynk.user'. Error : No content to map due to end-of-input
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 0]
20:40:08.184 INFO - Trying to recover from backup...
20:40:08.199 INFO - Found /opt/blynk/data/backup/....Blynk.user.2019-01-24. You are lucky today :).
20:40:08.591 INFO - Restored.
```

version: `0.41.3-SNAPSHOT`

**Comment by doom369** [comment]
@bestpika this error not related to the raw data. It is error during profile reading. However, server does backups (locally) so this is not an issue.

**Comment by bestpika** [comment]
But when profile crash, it can't recover, so how do I enable local backup?

**Comment by doom369** [comment]
By copy of `data` folder.

**Comment by bestpika** [comment]
So it can't re-enable auto backup?
