### ISSUE TITLE
How to determine widget?

### ISSUE THREAD

**Issue by rwaldron** [blynkkk/blynk-server#131]
How can I determine what kind of widget produced a message? For example, using the following program: 

```js
var Blynk = require("blynk-library").Blynk;
var blynk = new Blynk(process.env.BLYNK_TOKEN, {
  board: {
    blynk: null,
    init: function(blynk) {
      this.blynk = blynk;
    },
    process: function(values) {
      console.log(values);

      return true;
    }
  }
});
```

If I add two buttons to the stage, how does the program know they are buttons?

```
$ node index.js
Connecting to SSL: cloud.blynk.cc 8441
Connected
Authorized
[ 'pm', '0', 'out' ]
[ 'dw', '0', '1' ]
[ 'dw', '0', '0' ]
[ 'dw', '0', '1' ]
[ 'pm', '2', 'out', '0', 'out' ]
[ 'dw', '2', '1' ]
[ 'dw', '2', '0' ]
[ 'dw', '2', '1' ]
[ 'dw', '2', '0' ]
[ 'dw', '2', '1' ]
```

**Comment by doom369** [comment]
You can't do that from hardware.

**Comment by rwaldron** [comment]
Why? Couldn't the widgets have a widget code?

**Comment by doom369** [comment]
Sorry. What do you mean by "widget code"?

**Comment by rwaldron** [comment]
I mean, there could very easily be an associated byte code for each widget. It's kind of crazy that there is no way for the iOS (or android, or whatever) app to tell the code on the hardware what was pressed from within the app. A reasonable protocol would've taken this into consideration.

**Comment by doom369** [comment]
> there is no way for the iOS (or android, or whatever) app to tell the code on the hardware what was pressed

There is such way. But as I said this is not possible from hardware side as hardware doesn't use this info in any way.

Blynk has better abstraction - PINs. There is not need to rely on other abstractions like widgets as this is not flexible.
So you work with PINs - analog, digital, virtual and based on PIN type and index you could define which widget is used.

**Comment by rwaldron** [comment]
Yes, thank you—I've made myself familiar with how Blynk works, the protocol is not complicated and is generally the information that's used in other similar wire protocols that I've worked with and written. I was just hoping that I could more information; but if not, I can make do. Thanks.

**Comment by doom369** [comment]
Well, if you really need something and this is missing at the moment - please create ticket. We are eager to help and tying to make Blynk community driven =).
