### ISSUE TITLE
A list of connected devices!

### ISSUE THREAD

**Issue by dmamontov** [blynkkk/blynk-server#1311]
Good day! Can we get a list of all devices from DeviceSelector in any way? I really needed this opportunity! Since in the implementation of many devices and various DeviceSelector's.

I also wanted to be able to use some kind of Master key to gain access to these devices through a bridge from others.

Would do it myself. But far from Java. The api method is easy to implement, but through web sockets it would be more correct!

Thank!

**Comment by doom369** [comment]
Hello. Will be available in Blynk 2.0. That is under development currently.

**Comment by dmamontov** [comment]
> Hello. Will be available in Blynk 2.0. That is under development currently.

And when will be version 2?

**Comment by doom369** [comment]
Probably at the end of May.
