### ISSUE TITLE
Can't create a new account on my blynk local server

### ISSUE THREAD

**Issue by adjian** [blynkkk/blynk-server#1316]
Hi Blynk experts,

Blynk app version: 2.16.11
Blynk local server version: server-0.41.4

I apply a account of gmail and create a blynk local server base on guide(https://github.com/blynkkk/blynk-server). 
As a result:
1. I can login to local server homepage by port 9443.
2. I can't create a new account through blynk app.
3. I try to capture the network packages through wireshark, and I found that, there are some TLS handshake packages and some "Application data "on network between blynk app and local server. but my app still show "connecting..." and can't create account successfully.

Last thing is that, I'm in China, for some reason I can't login Gmail directly from my home, but I really have a gmail account and set gmail configuration base on guide. I'm not sure whether it is the root cause of this issue.

That all. 
If you need more detail info, please let me know. I really need your help.

Thank you.

**Comment by doom369** [comment]
> Blynk app version: 2.16.11

Please try the latest one.

**Comment by adjian** [comment]
@doom369 
I have install the newest Blynk app, and now it work well.
Thank you for your help.

Now, I will close this ticket.
