### ISSUE TITLE
Default login can be changed from admin@blynk.cc to one without an @ sign

### ISSUE THREAD

**Issue by rozza-m** [blynkkk/blynk-server#1317]
As in title, it's possible for a novice user to use the web interface to change the "email address" field to one without an @ sign. It cannot be used to login because an @sign is required to submit login, leaving user with no way to login.

**Comment by doom369** [comment]
@rozza-m thanks. Fixed.

**Comment by rozza-m** [comment]
Fast work!! Thanks very much!
