### ISSUE TITLE
Web admin interface doesnt save changes to server.properties

### ISSUE THREAD

**Issue by Phil1988** [blynkkk/blynk-server#1318]
Hello everyone!

I am running dietpi (lightwheight port of debian) on a virtual machine.
However, all changes I make on the web admin interface are not saved to the server.properties and therefore lost after a service restart.

The server.properties only represents the acutal version of the real server.properties file.
Is this the expected behaviour from the web admin interface or should it actually save the settings in the file?

**Comment by doom369** [comment]
Hello, yes, this is expected and was never actually implemented. You need to manually fix the file before server start.
