### ISSUE TITLE
Checksum for release

### ISSUE THREAD

**Issue by 6wheels** [blynkkk/blynk-server#1322]
Hi,
I'm the maintainer of the AUR package for Archlinux.
A checksum is made to ensure the downloaded sources are correct.

But actually, what I do is:
1. download the .jar manually
2. compute the sha256 locally
3. modify my package build info accordingly

I can't be sure at step 2 that my downloaded jar file is actually the right one.

That's the object of this issue.
I've already seen it on other github projects: it would be great to provide, on the release page, the sha256 computed during the build of the jar.

Thanks.

**Comment by doom369** [comment]
@6wheels can you please point me to the examples of how this is done on the other projects?

**Comment by 6wheels** [comment]
https://github.com/keepassxreboot/keepassxc/releases provides them as assets.
I think this is enough. And assets are available through the github api, so this could automate the process for my packaging.
I don't know if there is a better way, like displaying the checksum somewhere else in the release block.

**Comment by 6wheels** [comment]
Hi @doom369,
After a few months :), I made some research and found this maven plugin http://checksum-maven-plugin.nicoulaj.net/
It seems to be the only maven plugin to provide a checksum file. The official `mvn:install` provides a checksum but it's generated in the repository folder, not in the target.

This can be added to your `pom.xml` and your `.travis,yml` you publish it to the github assets.

**Comment by doom369** [comment]
Thanks. I didn't find any "quick" solutions, so for now I have to close it. At the moment Blynk 1.0 is not supported (except for the bug fixes). WE are on the final stage of the launch of Blynk 2.0. So all efforts are focused on the new version. Stay tuned.
