### ISSUE TITLE
Blynk on local server - Mail configuration

### ISSUE THREAD

**Issue by harkor** [blynkkk/blynk-server#1324]
Hello,

I installed blynk on my webserver and I use sendgrid smtp to send mails.

The problem is mail.smtp.username is used in "From" aswell.

It's possible to add in the config something like "mail.smtp.from=example@example.com" ?

For instance, I have "mail.smtp.username=apikey" because sendgrid need that and emails flagged in spam because "apikey" isn't a mail and not allowed. 

Thanks

**Comment by doom369** [comment]
Already there - `mail.from=xxx`

**Comment by harkor** [comment]
It's in the documentation ?
I didn't find in server.properties
