### ISSUE TITLE
Blynk android app can not scan QR code on local server

### ISSUE THREAD

**Issue by tackelua** [blynkkk/blynk-server#1330]
I can not scan qr code to clone project on **local server**.
It show a invalid blynk qr code
Please check if it's works for you!
Thank you so much!

**Comment by kenken64** [comment]
Enabling QR generation on server
    sudo apt-get install libxrender1

**Comment by thinhbgnex** [comment]
> Enabling QR generation on server
> sudo apt-get install libxrender1

Thank you, but I run blynk server on windows. Have any package instead?

**Comment by doom369** [comment]
@tackelua do you see some error in the logs?

**Comment by phanluan1101** [comment]
Hello, I'm also facing the same problem that the QR code cannot be generated with my project using on a local server. Is there a way I can config my server so it can generate a cloning QR code? I'm using Windows Server 2012 R2

**Comment by doom369** [comment]
Sorry, this feature wasn't designed to work under windows. Also, right now I don't have time to investigate the possible fix for it, so I have to close this ticket.
