### ISSUE TITLE
Wrong <Text Input> height while text editing 

### ISSUE THREAD

**Issue by Allineer** [blynkkk/blynk-server#1331]
Blynk App 2.27.6
Android 9, MIUI 10

I have some Text Input field. In edit mode it's looks like this:

![image](https://user-images.githubusercontent.com/1168049/62045760-e1420f80-b20e-11e9-8d26-50e855b6221a.png)

But, in the Play mode when I edit it's content, it's looks like this:

![image](https://user-images.githubusercontent.com/1168049/62045776-ee5efe80-b20e-11e9-9951-09285a2f05ee.png)

Did you see that? Why the control's height is smaller?

Thanks.

**Comment by alexkipar** [comment]
@Allineer can you attach the version number of the app - you can check it on the about screen (press on the info button of projects list screen)

**Comment by Allineer** [comment]
@alexkipar, this?

![Screenshot_2019-07-29-13-48-19-974_cc blynk](https://user-images.githubusercontent.com/1168049/62042862-bdc79680-b207-11e9-92c7-b60c3a8cc738.png)

**Comment by alexkipar** [comment]
@Allineer thanks, can you send logs via Gmail? we had worked on this bug, but looks like in some cases it is still an issue,

**Comment by Allineer** [comment]
@alexkipar logs was sent with this issue number in the email message.

**Comment by alexkipar** [comment]
@Allineer We just released a 2.27.7 build with a possible fix to this bug and with enhanced logs - please send the log after update and app's run.

**Comment by Allineer** [comment]
@alexkipar, Ok. Waiting for the update will be available for installation...

**Comment by Allineer** [comment]
@alexkipar It's fixed! Lоgs was sent.

Спасибо!

**Comment by doom369** [comment]
@Allineer спасибо за репорт!
