### ISSUE TITLE
Broken link in the <Push Notifications> decription

### ISSUE THREAD

**Issue by Allineer** [blynkkk/blynk-server#1332]
Blynk App 2.27.6

About \<Push Notifications\> activity.
Priority description block - "См. более подробное обьяснение здесь." line - link is broken (404).

![Screenshot_2019-07-29-19-58-42-297_cc blynk](https://user-images.githubusercontent.com/1168049/62070092-7ca0a800-b242-11e9-8d85-624d36bf8ce3.png)

**Comment by doom369** [comment]
Thanks! Fixed.
