### ISSUE TITLE
Share App cannot set Timer

### ISSUE THREAD

**Issue by Permpol** [blynkkk/blynk-server#1336]
If use main app Timer ok. But share app if set timer it reset time old.
• Hardware model + communication type. For example: Arduino UNO with Ethernet Shield
-I use ESP32 and ESP8266

• Smartphone OS (iOS or Android) + version
-All iOS and Android

• Blynk server or local server

local server
• Blynk Library version
server-0.41.9.jar

Install on Ubuntu 16.04.4 x64

I use widget timer normal

https://www.youtube.com/watch?v=XVCge62lU24

**Comment by doom369** [comment]
Hello. That's correct. Share app is designed only for demo purposes.
