### ISSUE TITLE
Eventor TIMED - Send Email

### ISSUE THREAD

**Issue by bhyatyab** [blynkkk/blynk-server#1339]
Hi

There is an issue with TIMED "send email" in the eventor widget for android. Emails are not working. Emails are working for other widgets and other options in eventor but not for a TIMED event.

Please advise.

Regards.

**Comment by doom369** [comment]
Hello. More details would be helpful. Server setup, eventor setup, email, etc.

**Comment by bhyatyab** [comment]
I tried the same config on a rasberry pi local server and also the blynk cloud server

I'm running have Samsung S8 running Android 9 with the latest blynk app.

The eventor config is to send a daily email at 7pm everyday with the message "Test Email".

Sending emails from other parts of the app work with the exception of timed eventor emails

**Comment by doom369** [comment]
Do you use the same email? Is it correct?

**Comment by doom369** [comment]
@bhyatyab do you have email widget in your project?

**Comment by bhyatyab** [comment]
Yes i have the email and notification widget. Emails work in the eventor for eg pin change status but not for TIMED events

**Comment by doom369** [comment]
@bhyatyab is the email within mail widget correct? Please double check it doesn't have any hidden characters.

**Comment by bhyatyab** [comment]
Yes email is correct. I tested this on local and cloud server - new setup. I get email from eventor with pin change etc but just not with the TIMED option in eventor

**Comment by doom369** [comment]
Please post your rule settings within Eventor.

**Comment by doom369** [comment]
@bhyatyab no need. I found the problem. Will fix ASAP.

**Comment by bhyatyab** [comment]
Cool. Is it and issue on the android app or blynk server

**Comment by doom369** [comment]
It seems that I done this by purpose. Sending email with time event doesn't make any sense. This is because you can't specify a pin to send in that case. Could you please clarify what is your use case?

**Comment by bhyatyab** [comment]
im just looking to get a daily email to say the nodemcu is online

**Comment by doom369** [comment]
You can try notification widget with "notify when offline" option.
