### ISSUE TITLE
Local Blynk Server Admin Page

### ISSUE THREAD

**Issue by bhyatyab** [blynkkk/blynk-server#1341]
Hi

- Please advise as to how I can block access to my Local Blynk Server Admin Page over the internet. Im running a raspberry pi and I have port forwarding enabled on my router. I just want the admin page accessible from within my local network not from over the internet.

- I configured port forwarding as 8443 external goes to internal 9443. It connects to my blynk application - is this the preferred method?

Thanks

**Comment by doom369** [comment]
> I just want the admin page accessible from within my local network not from over the internet.

use `allowed.administrator.ips` option

For further questions please use https://community.blynk.cc/
