### ISSUE TITLE
404 Error for jar file

### ISSUE THREAD

**Issue by DubbyHarry** [blynkkk/blynk-server#1345]
pi@raspberrypi:~ $ wget "https://github.com/blynkkk/blynk-server/releases/download/v0.41.10/server-0.41.11-java8.jar"
--2019-09-25 19:50:52--  https://github.com/blynkkk/blynk-server/releases/download/v0.41.10/server-0.41.11-java8.jar
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-09-25 19:50:52 ERROR 404: Not Found.

**Comment by doom369** [comment]
@DubbyHarry thanks. Url fixed.
