### ISSUE TITLE
/admin panel on http port

### ISSUE THREAD

**Issue by Allineer** [blynkkk/blynk-server#1349]
Hello!

The admin panel does not work with the http (8080) port and redirects to https://blynk.cc.

Is it possible to change this behavior and open the admin panel on the http port?
This is necessary in order to place the admin panel behind nginx as a reverse proxy and not use built-in self-signed certificates.
In my case, the real SSL certificates are on nginx, which is on completely different servers.

С английским языком у меня всегда были сложности, уж простите.
Есть возможность открывать панель администратора на указанном plain-HTTP порту?

**Comment by doom369** [comment]
Hello. This possibility was removed on purpose and currently not supported. However, you can fork the code and change this.

**Comment by Allineer** [comment]
Thanks.

**Comment by Allineer** [comment]
Resolved, but in a slightly different way.

Related to:
https://community.blynk.cc/t/nginx-reverse-proxy-with-blynk-server/27918/4
https://community.blynk.cc/t/use-reverse-proxy-in-front-of-blynk-local-server/25552/8

Blynk server is listening on 192.168.255.2:9443 with default self-signed certificates.

`/etc/nginx/nginx.conf`:
```
stream {
    map $ssl_preread_alpn_protocols $upstream {
       ~\bhttp/1.1\b  127.0.0.1:443;
       default        192.168.255.2:9443;
    }

    server {
        listen 111.222.333.444:443; # my external ip
        proxy_pass $upstream;
        ssl_preread on;
    }
}
```

`sites-available/blynk.example.com`:
```
server {
    listen 127.0.0.1:443 ssl;
    server_name blynk.example.com; # subdomain only for the Blynk admin panel

    include /etc/nginx/conf.d/ssl.conf;
    ssl_certificate     /.../fullchain.pem; # correct certificates
    ssl_certificate_key /.../privkey.pem; # correct certificates

    access_log off;
    error_log /dev/null crit;

    location / {
        proxy_pass https://192.168.255.2:9443;
        proxy_set_header X-Forwarded-Ssl on;
        include /etc/nginx/proxy_params;
    }
}
```
And that’s all.

А подробности на русском, уж простите:
Решение косячное, но другого пока не вижу особо. В результате весь неопознанный входящий трафик на порт 443 отправляется серверу Blynk as-is.
Весь HTTP-трафик заворачивается на 127.0.0.1:443 и дальше обрабатывается vhost-ами Nginx как обычно.
Выделенный vhost работает как reverse-proxy для админки Blynk и отдает пользователю корректные сертификаты.

Мобильный клиент вполне себе корректно подключается к этой пирамиде, т.к. он приучен еще разработчиками игнорировать самоподписанные сертификаты.
Самописные библиотеки на python и С тоже отучены придираться к левым сертификатам и вполне себе работают.

**Comment by Allineer** [comment]
На самом деле, ребят, спасибо вам за действительно крутое решение, но... что сам протокол, чтоо подход "самописный бинарный протокол + HTTP на одном порту в собственном приложении" - это жесть.
