### ISSUE TITLE
White Terminal backgroung in the light theme

### ISSUE THREAD

**Issue by Allineer** [blynkkk/blynk-server#1350]
Blynk App 2.27.10
Android 9, MIUI 10

I'm using Terminal widget as a short log (without the input line).
And I would like to see a white background on it.
With a dark app theme is't not a problem:

![Screenshot_2019-10-16-07-57-07-415_cc blynk](https://user-images.githubusercontent.com/1168049/66889641-e764b280-efeb-11e9-8fbc-7df3fac50fbb.png)
![Screenshot_2019-10-16-07-57-11-782_cc blynk](https://user-images.githubusercontent.com/1168049/66889642-e764b280-efeb-11e9-9d83-a226ec743ed4.png)

Difficulties arise when using a light theme.
The white background of the widget for some reason becomes inaccessible, so I'm trying to get out by moving the contrast slider for black color and, at first glance, this solves the problem:

![Screenshot_2019-10-16-07-57-36-072_cc blynk](https://user-images.githubusercontent.com/1168049/66889643-e764b280-efeb-11e9-9512-fd299fb234fb.png)
![Screenshot_2019-10-16-07-57-40-453_cc blynk](https://user-images.githubusercontent.com/1168049/66889644-e7fd4900-efeb-11e9-83a7-a0c87942c0ee.png)

But this helps exactly until the application is restarted. After it, the background color turns black again:

![Screenshot_2019-10-16-07-57-53-024_cc blynk](https://user-images.githubusercontent.com/1168049/66889645-e7fd4900-efeb-11e9-9503-769f1021b356.png)

The application log was sent to the mail.

Can this be fixed?
Thanks.

**Comment by doom369** [comment]
Thanks for the report. We will check.

**Comment by Allineer** [comment]
Fixed in 2.27.11
Thanks!
