### ISSUE TITLE
sudo apt-get install oracle-java8-jdk not working 

### ISSUE THREAD

**Issue by Firemanpl** [blynkkk/blynk-server#1351]
pi@raspberrypi:~ $ sudo apt-get install oracle-java8-jdk
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package oracle-java8-jdk is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'oracle-java8-jdk' has no installation candidate

**Comment by Firemanpl** [comment]
I have rpi zero W

**Comment by doom369** [comment]
You can find other alternatives, like here - https://www.raspberrypi.org/forums/viewtopic.php?t=199813
