### ISSUE TITLE
Providing timestamp for data uploaded via REST API

### ISSUE THREAD

**Issue by ondrej1024** [blynkkk/blynk-server#1354]
Is it possible to provide a timestamp when uploading data via the REST API?

Looks like a timestamp is added by the server to data related to a graph widget when it is uploaded. But I would like to do a bulk upload of many data points, each with its own timestamp. How can this be done?

Thanks

**Comment by doom369** [comment]
Hello. This is not supported. It is available only in the new Blynk version that is not yet public.

**Comment by ondrej1024** [comment]
OK, thanks for the information.
