### ISSUE TITLE
Android system cannot select custom server

### ISSUE THREAD

**Issue by Permpol** [blynkkk/blynk-server#1359]
I use mobile android cannot select is custom server. Once selected, it switches back to the original blynk server. I use `oasiskit.com` .But IOS normal.

**Comment by doom369** [comment]
What android version and phone version?

**Comment by Permpol** [comment]
> What android version and phone version?
> […](#)

https://drive.google.com/file/d/1ir8GHkWG9Nfe2gmKD_hoXKg2qok4uIDC/view?usp=drivesdk

And Blynk version

https://drive.google.com/file/d/13OjHqTLQnRTdTVzmcXyhcE9-NRvT0FVx/view?usp=drivesdk

Now I use fix down version is 2.27.0 can use no problem

**Comment by gsgameiro** [comment]
I cannot select **oasiskit.com** server, so I got the external IP of **oasiskit.com** that is 128.199.173.118 and it works.
Blynk version: 2.27.12
Running in Android version 9

**Comment by MasterCATZ** [comment]
same boat can not work out how to get Android application to look at my server  2.27.12

**Comment by doom369** [comment]
Thanks for the report. We will check.

**Comment by doom369** [comment]
Those domain was blacklisted as it is violates Blynk licensing. So this expected.
