### ISSUE TITLE
Webhook. HTTP 202 is valid response

### ISSUE THREAD

**Issue by tobiascrackz** [blynkkk/blynk-server#1362]
pls add 202 to valid responses in blynk server webhook

**Comment by doom369** [comment]
@tobiascrackz done. thanks!

**Comment by tobiascrackz** [comment]
thank you very much @doom369 ! great job! just downloaded the latest build again and run it on my raspberry but the problem persists (kill old version, delete it, download latest build, run it). how do i implement the improvement now?

**Comment by doom369** [comment]
@tobiascrackz I haven't provided build yet.

**Comment by doom369** [comment]
@tobiascrackz java 11 build - https://github.com/blynkkk/blynk-server/releases/download/v0.41.12/server-0.41.13-SNAPSHOT.jar

**Comment by tobiascrackz** [comment]
@doom369 that was fast, great :)) sadly I'm running Java 8 on a Raspberry Pi :(( will newer versions of Blynk server not support Java 8?

**Comment by tobiascrackz** [comment]
ok, i updated to Java11. Now everything is running perfect. If anybody else is looking for a good guide on how to install Java 11 on rPi:

http://hirt.se/blog/?p=1116
