### ISSUE TITLE
Server release 41.13 is missing the Java 8 version

### ISSUE THREAD

**Issue by chrissv** [blynkkk/blynk-server#1366]
Server release 41.13 is missing the Java 8 version. I only see the jar file without the text "-java8" in it.

**Comment by doom369** [comment]
Hello. Will provide it soon. Busy with server updates.

**Comment by doom369** [comment]
Added - https://github.com/blynkkk/blynk-server/releases/download/v0.41.13/server-0.41.13-java8.jar

**Comment by chrissv** [comment]
Awesome, thanks! Didn't mean to jump the gun...
