### ISSUE TITLE
Cannot connect my local server from outside

### ISSUE THREAD

**Issue by dobl1** [blynkkk/blynk-server#1367]
Hello,
First of all thank you for Blynk, incredible project!

I have a **Blynk Server instance running on a raspberry pi** at my home. I also have a **server that acts as a reverse proxy** so I can access blynk from the outside.

In my browser (external network) I access the blynk admin interface without any issue (https://blynk.mydns.com -> mydns.com reverse proxy -> 192.xxx.xxx.xxx:9443 ok) but in the application (Android ) **I get stuck on "Connecting ..." entering my credentials and blynk.mydns.com with port 443.**

Did I miss or do something wrong?

Thanks for your help.

**Comment by doom369** [comment]
Please use https://community.blynk.cc/ for your questions.
