### ISSUE TITLE
Shouldn't creating a unique username and password be part of the first time server start, instead of a default?

### ISSUE THREAD

**Issue by light24bulbs** [blynkkk/blynk-server#1368]
Most people are going to point this server to the internet via port forwarding.  Changing the username and password isn't even mentioned as an important step in your setup guide, and it's not all that clear how to do it.  A lot of people might skip it.  Seems like Blynk-server writes its username and password on first time startup, why not prompt the user at that point?

**Comment by DANSI** [comment]
I agree, that a default username and password isn’t a good idea, if the Server is mapped to the internet. I think an autogenerated user/pass pair is better. Server can write it to console at first start, so lazy users would get a little more secure user/pass combination.

**Comment by light24bulbs** [comment]
I've also been fairly impressed by the "adjective-noun" password
generators, if you're looking for something more human readable than a
pseudorandom string.

**Comment by doom369** [comment]
Thanks, agree. NOw password will be auto-generated and printed on the initial server start to the console.
