### ISSUE TITLE
Webhook HTTP 201 is valid response

### ISSUE THREAD

**Issue by hni65** [blynkkk/blynk-server#1369]
I’m trying to send values to Opensensemap.org using the Webhook widget on a local server in Docker container. Everything works fine, except that the Webhook stops after a short time sending the data.

According to the documentation valid HTTP response is only 200 or 302 and will stop sending after 10 times, but POST response from Opensensemap is 201 (“Measurements saved in box”)

Can you change Blynk to accept HTTP response 201 as a valid response?

Thanks 
Harald

**Comment by doom369** [comment]
@hni65 hello. Fixed. Deploy will be done in a few weeks. Or you can use local server instead.
