### ISSUE TITLE
Any reason why Blynk doesn't use REST for its HTTPS? (reverse proxying question)

### ISSUE THREAD

**Issue by laimison** [blynkkk/blynk-server#1372]
Hi,

Sorry for my unawareness on Blynk internals.

Is there some technical limitation or some standard/convienient way for mobile to not use REST?

I would see the value from reverse proxying perspective:

1) CDN to hide IP and protect from attacks, improve security
2) If using Kubernetes, you can make this Blynk highly available through Ingress (Nginx proxy) as other standard services
3) Less ports to outside, not dedicating port specifically for Blynk
4) Some people organise all services in reverse proxying world so no exclusion would be required for Blynk

If that can't be achieved, maybe it is possible to send non HTTP data through an additional non HTTP port to deal with it separately?

I'm referring to this issue https://github.com/blynkkk/blynk-server/issues/1340

Many thanks

**Comment by doom369** [comment]
Hello, in general, you're right.

There are a lot of benefits for Blynk from the REST. However, the initial purpose of the Blynk solution was to create as fast and as cheap solution as possible. And by cheap I mean the cost of handling 1 device. While reverse proxies add more overhead, increase the cost of the infrastructure, and bring more complexity to the system in general. Also, reverse proxies itself are not a  silver bullet, they have their own vulnerabilities. Another thing - we don't use any standard HTTP server, we use our own server with minimum required functionality.

> I'm referring to this issue #1340 

I think nginx could forward the Blynk hardware traffic, however for that you need to use TCP/IP forwarding, not HTTP forwarding as it was done in the above ticket - https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer.

**Comment by sakurai-youhei** [comment]
@laimison @doom369 Just FYI but I have worked out reverse-proxying blynk-server by Nginx recently. [HERE](https://gist.github.com/sakurai-youhei/9a664f2697e599dcaa939091ffff9816) you are if interested.

**Comment by laimison** [comment]
Thanks @sakurai-youhei , I'll give a try with this solution! By the way many thanks for your involvement guys and a great product.
