### ISSUE TITLE
hardware SSL connection does not work

### ISSUE THREAD

**Issue by tom-ch1** [blynkkk/blynk-server#1374]
I have a blynk server blynk-server-0.41.13.jar set-up using Let's Encrypt certificates and an esp8266 board as well as an android blynk-App up and running. The App can connect to my server using ssl. The hardware works perfectly when not using SSL. However, the hardware can not connect using SSL. The code of the example generator (https://examples.blynk.cc/) for SSL does not work!

The documentation on http://docs.blynk.cc/#security states:

"9443 - SSL/TLS connection for the Mobile Apps on the Local Server and hardware with SSL"
so it seems that the hardware should be able to connect to the same port than the mobile App.

The documentation on https://github.com/blynkkk/blynk-server#advanced-local-server-setup states:
"Blynk app, https, web sockets, admin port
https.port=9443"
so it seems that the common ssl port can be configured using the https.port parameter in server.properties

That does not work! The log on the hardware just repeats: "Connecting to my.server.name:9443"
But it never successfully connects. The server log contains no trace of connection attempts. The mobile App connects just fine.

Some sites mention other server.properties parameters such as app.ssl.port, hardware.default.port, hardware.ssl.port none of which are neither documented nor work as expected.

How can my hardware connect to my blynk server using SSL?

**Comment by tom-ch1** [comment]
trace output of server:
01:21:36.204 TRACE- Blynk server IOException.
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

The Serial Monitor of the hardware (with BLYNK_DEBUG set) only repeats: "Connecting to my.server.name:9443"

**Comment by doom369** [comment]
@tom-ch1 hello. What hardware do you have?

**Comment by tom-ch1** [comment]
Hi, it's a Sonoff Basic

**Comment by tom-ch1** [comment]
Oh, come on, you really just wasted my (and I'm sure thousands of users') time by not properly documenting how to make SSL work with a self-hosted server. It took me several days and a code-review to find the solution:

If you have your own blynk server and you use SSL, then IT IS NOT SUFFICÌENT TO FOLLOW THE DOCS:
- First, follow the obvious instructions in the docs (but you probably did that already):
  - https://github.com/blynkkk/blynk-server#advanced-local-server-setup or 
  - https://github.com/blynkkk/blynk-server#manual-lets-encrypt-ssltls-certificates 
- AND THEN, FOLLOW THIS UNDOCUMENTED STEPS TO MAKE YOUR ARDUINO SKETCH WORK:
  - If you don't use Let's Encrypt Certificates, you'll have to edit the code. I won't cover it here, I just give you the pointer: ./libraries/Blynk/src/BlynkSimpleEsp8266_SSL.h: #if defined(BLYNK_SSL_USE_LETSENCRYPT)
  - If you use Let's Encrypt certificates, you'll have to add "#define BLYNK_SSL_USE_LETSENCRYPT" BEFORE "#include <BlynkSimpleEsp8266_SSL.h>" in the Arduino Sketch for your hardware. Tools--> SSL support in the Arduino IDW is completely irrelevant. No matter what you select there, it won't work!

Please please please, just add it to the docs!

**Comment by doom369** [comment]
@tom-ch1 thanks for the update. Doc updated. Sorry for your time.
