### ISSUE TITLE
I have issue!

### ISSUE THREAD

**Issue by deeg05** [blynkkk/blynk-server#1376]
For some reason, my blynk server started to listen only on ipv6
server.properties:
```
https.port=9443
  http.port=8081
  admin.email=blynk.admin@deeg05.ml
  admin.pass=du10008@award
  contact.email=deeg05@mail.ru
```
jar version: server-0.41.5-java8.jar
```
~$ sudo netstat -tanp | grep 8081
tcp6       0      0 :::8081                 :::*                    LISTEN      13025/java          
~$ sudo netstat -tanp | grep 9443
tcp6       0      0 :::9443                 :::*                    LISTEN      13025/java    
```

**Comment by doom369** [comment]
@deeg05 hello. Strange, by default all interfaces should be bounded. Anyway, you can try to set `listen.address=0.0.0.0` in the `server.properties`. That should help.

**Comment by deeg05** [comment]
Doesn't resolve the issue :( 
I found out, that probably ipv4 is working, but somehow only locally on the server. Any ideas?

**Comment by deeg05** [comment]
Oh, I realised that my server is using nftables instead of iptables and ports there weren't accepted :^)
Thanks anyways!
