### ISSUE TITLE
Can we have a static link to latest java8 release?

### ISSUE THREAD

**Issue by 877dev** [blynkkk/blynk-server#1377]
Hello,

The latest version link is:
https://github.com/blynkkk/blynk-server/releases/download/v0.41.14/server-0.41.14-java8.jar

For Docker users, we need to manually change the Dockerfiles for each version release. It would be nice if there was also a static "latest" java8version link such as:
`https://github.com/blynkkk/blynk-server/releases/download/latest-java8.jar`

Is that possible?

**Comment by Zephael86** [comment]
@877dev do Docker (SensorsIot/IOTstack) users really require java8 and not the normal server-x.y.z.jar link?

**Comment by doom369** [comment]
I didn't find anything like that on the girhub. So looks like not.
