### ISSUE TITLE
ADD A BETTER README FOR SERVER.PROPERTIES

### ISSUE THREAD

**Issue by gptshubham595** [blynkkk/blynk-server#1382]
Please add a better readme for server.properties
I am really frustrated now on this.!!

I have downloaded server.jar create server.crt,server.pem, mail.properties[default with my gmail and pass with less secure on], server.properties[same as yours only I changed is this line as I don't gave any psswd to create crt]

![image](https://user-images.githubusercontent.com/24877361/97806931-10ea8d80-1c84-11eb-8bc2-7fe781f1e368.png)

Now any IP even localhost redirects to BLYNK.IO and NOT ADMIN PANEL please help

I tried my ipv4 address with 8080, 9443, 8000 with and without /admin but it redirects 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/24877361/97807365-5445fb80-1c86-11eb-824d-4179f2aba60f.gif)

I tried without server file also same result NOT WORKING HELP

![image](https://user-images.githubusercontent.com/24877361/97807311-18ab3180-1c86-11eb-9a34-e489cb16a7cf.png)

**Comment by doom369** [comment]
You should use full path with "/admin", also according you the output you have unnecessary space before the "admin" word

**Comment by hznupeter** [comment]
https NOT http
