### ISSUE TITLE
map.strings.pool.size property not working 

### ISSUE THREAD

**Issue by eiriksels** [blynkkk/blynk-server#1397]
I am trying to increase the map.strings.pool.size value in server.properties but it seems like I am stuck with the default 25. I also tried to decrease the pool size without success.

I have tried updating other properties in server.properties and they all work. Can I get a confirmation on if this is just an issue on my side?

Blynk Server version: 0.41.15

**Comment by doom369** [comment]
@eiriksels should be fixed in the latest version I just released.

**Comment by eiriksels** [comment]
I can confirm that it works now. Thanks!
