### ISSUE TITLE
Uninstall from pi

### ISSUE THREAD

**Issue by ESF-nl** [blynkkk/blynk-server#1398]
After installing Blynk server my wife is angry to me because she has to go to the toilet in the dark :-( 
The Blynk server conflicts with my Domoticz server on port 8080.  I tried to uninstall blynk but do not know how. I removed all files by sudo rm and sudo rm -r but as soon as I enter my pi local IP 192.168.0.176:8080 to reach Domoticz I'm forwarded to the external site https://blynk.io/

Via Google and under closed issues I cannot find the right way to uninstall. Would you please help me?

**Comment by ebolisa** [comment]
Cannot you change the port number on either platforms? 🤔

**Comment by ESF-nl** [comment]
Yes, that would be best but I don't know how. I won't like to change the domoticz port as many this are linked to that. 
Do you know the right command to change the Blynk port ?

**Comment by ebolisa** [comment]
Off head, server.property(ies)

**Comment by ebolisa** [comment]
https://github.com/blynkkk/blynk-server/blob/master/server/core/src/main/resources/server.properties

**Comment by ESF-nl** [comment]
Thank you ebolisa for your swift replies. Unfortunately I cannot find the file server.properties inside the Blynk folder on my pi. Would you please give a beginner as I am some more directions?

**Comment by ebolisa** [comment]
Please search/ask in the forum (link shown above) as there’s lot of info on this issue.

**Comment by ESF-nl** [comment]
Uninstall question is not answered but I close this issue because server.properties is working now and the toilets lights as well...
