### ISSUE TITLE
Controlled Number of Users (User Limit)

### ISSUE THREAD

**Issue by mgonline** [blynkkk/blynk-server#1400]
**Background:**
Blynk is a great project which I have been using for all my personal projects now (kudos to all the blynk-server maintainers and contributors). I have recently set up a ddns to my local blynk server so that I can access it remotely. Everything works!

**Problem:**
The problem is, I can register as many accounts as I want. This might be okay for a public blynk server, however, for a personal server, I only want a controlled number of registrations. I've searched a lot to achieve this, but couldn't find any setting for it. So I think this ticket will land as a feature ticket. 

**Possible solutions:**
As per my viewpoint, this can be done in either of the following ways:
- Specifying _max number of users_ in `server.properties`. I know there's a limit on the number of devices each account can have `"user.devices.limit"` and also there's a hourly registration limit `"hourly.registrations.limit"`. I'm talking about total number of users that can exist on the server - something like `"user.limit"`! This will require changes in `Limits.java` and `MobileRegisterHandler.java`.
- Manually approving the registrations. The users can register themselves, but it'll be initially in an _inactive_ state and won't be able to login from any of their devices. Only if I (the admin) manually enable that user from the admin portal, they'll be able to login.

Thanks!

**Comment by doom369** [comment]
@mgonline hello. Blynk-server is on maintenance mode, meaning we won't add anything new except the bug fixes. You are free to fork it and extend it as you wish.

**Comment by mgonline** [comment]
Whoa! That's sad news! Is it going to be permanent? Is this project going EOS / EOL? If that's the case, it'll be great if you can point me to some detailed public communication.
