### ISSUE TITLE
Would like to keep all minute records on Blynk local server

### ISSUE THREAD

**Issue by kylechen1980** [blynkkk/blynk-server#1408]
Hi:
I face a problem that minute records on Blynk local server will be erased after a period of time
Did the research and found that it might be solved by using db.properties

So if I want to keep all of the minute records, the only thing I need is a file named db.properties containing only a clause "clean.reporting=false" in it and put this file in the same folder as where server.properties stays, is that correct?

Or I have to deal with other db properties?

**Comment by doom369** [comment]
@kylechen1980 hi, you need to put desired interval into `server.properties` with property

`store.minute.record.days`
