### ISSUE TITLE
Create local server on new Blynk 2.0

### ISSUE THREAD

**Issue by HrithikDhongadi** [blynkkk/blynk-server#1411]
Hello everyone,
I normally would run my projects based on help of Blynk via its local server.
I was wondering if there is any way i can create a local server in the new Blynk 2.0 just like i used to create in the old Blynk.
Thankyou, and hope for the earliest reply.🙂

**Comment by doom369** [comment]
Hello. At the moment BLynk 2.0 doesn't have local server. And it's not in the plans for the next 6 months.
