### ISSUE TITLE
Can't create new account in local blynk server

### ISSUE THREAD

**Issue by Jaishankar872** [blynkkk/blynk-server#1417]
In November 2021, I have installed local blynk server in home and Blynk app from Google play store. 

But I am not create a new account (Register option is not showing) in Blynk app. 

Waiting for your response.

Thanks in advance.

**Comment by Schnullerbua** [comment]
@Jaishankar872 yes you can't but this is not a issue it is deaktivated in the blynk app. look in the FAQ and you will found :-)

**Comment by Jaishankar872** [comment]
@Schnullerbua Yes, I understand. But is there any possibility to enable for **Blynk local** server application alone ???

**Comment by Schnullerbua** [comment]
You can only use the admin account and change the mail and password. and if you create your own mail.properties and server.properties, all ist still working. sorry my english is not the best.

**Comment by Jaishankar872** [comment]
@Schnullerbua Thank you Let me try this method.
 Blynk server is running in Linux.

**Comment by Schnullerbua** [comment]
hi so i make a self test okay only under windows. there is a file look that   "admin@web.de.Blynk.user" and in this file Blynk store some data. look like this {"name":"Test_Blynk","email":"admin@web.de","appName":"Blynk","region":"local","ip":"192.168.178.48","pass":"mseLRx+P7ZPRrXzJ1v75psW51nN6191/HXc+WFfv3gE=","lastModifiedTs":1639544278038,"lastLoggedIP":"192.168.178.88","lastLoggedAt":1639517782376,"profile":{},"isFacebookUser":false,"isSuperAdmin":true,"energy":100000,"id":"admin@web.de-Blynk"}

this is for this test my fantasy mail. so wat i do is i copied the mail.Blynk.user file and i log in with my true user .. (Admin User) and it shows a new user. i dont know yet it work under linux but i have my Pi here an i will test ist. and i think if i write the true data in the mail.propertie file it will also working with my web mail adress. im not shure  yet. but this is my idea

**Comment by Jaishankar872** [comment]
Thank you for your support.


I tried a duplicate file which you mentioned with different token for different username but it is not working.


Note:
I am not expert in server or in Linux, now only  I am started to learn.

**Comment by Schnullerbua** [comment]
> Thank you for your support.
> 
> I tried a duplicate file which you mentioned with different token for different username but it is not working.
> 
> Note: I am not expert in server or in Linux, now only I am started to learn.

good thing is install a FTP look like this     sudo apt-get install pure-ftpd	<<< FTP install a FTP Server (pure)
after this you can easy download  this user file on you windows computer. me is use on my windows computer https://filezilla-project.org/      (Client) it's free

After this download from you PI this File admin@blynk.cc.Blynk.user
then rename it example: jasisankar@mail.com    << here use a real mail address
so now it is time to open your copied file with notepad++   (it's also free)
and you will see this:

{"name":"admin@blynk.cc","email":"admin@blynk.cc","appName":"Blynk","region":"local","ip":"192.168.178.200","pass":"yYeUQvFBH2sEC0WFhJFClld4E6b0szHlNlXiLUZ0EHo=","lastModifiedTs":1639550603843,"lastLoggedAt":0,"profile":{},"isFacebookUser":false,"isSuperAdmin":true,"energy":100000,"id":"admin@blynk.cc-Blynk"}      <-- this is the original file from your admin Blynk User

Now you can change in your copied file 

{"name":"Your_Name","email":"**test@mail.com**","appName":"Blynk","region":"local","ip":"IP from your PI","pass":"yYeUQvFBH2sEC0WFhJFClld4E6b0szHlNlXiLUZ0EHo=","lastModifiedTs":1639550603843,"lastLoggedAt":0,"profile":{},"isFacebookUser":false,"isSuperAdmin":true,"energy":100000,"id":"**test@mail.com-Blynk**"} 

save the File under a NEW Name

**test@mail.com.Blynk.user** you see the mail is important
after all upload your "new User File" in your Folder same as you found your origina admin@Blynk.cc.user file

Now log in with your Admin user an you see the new User and there you can change the password

thats it

i hope it's helps :-)  if u need more help we can meet in a discord??

**Comment by Jaishankar872** [comment]
It is working Now.
![image](https://user-images.githubusercontent.com/45547294/146556628-229959f1-d2ac-462f-b837-5b067caf11e7.png)

Thanks for your amazing support🙌🙌🎉
