### ISSUE TITLE
How to make a new account server-side?

### ISSUE THREAD

**Issue by chrisfoster121** [blynkkk/blynk-server#1425]
based on this forum post here: https://community.blynk.cc/t/blynk-2-0-personal-server/57897/9

account creation has been removed. This seems to me to be a huge  slap to the face to the open source community on top of no longer supporting local services. I don't know if this repo was the official but do you know if there is a way to make an account server side?

**Comment by doom369** [comment]
If you're an existing user "new acc" issue should not affect you.
If you're a new user you should use Blymk IoT.

Legacy Blynk apps and servers will be dismissed at some point.
