### ISSUE TITLE
Allowing third party apps closed after May 2022 Gmail

### ISSUE THREAD

**Issue by jason1987martis** [blynkkk/blynk-server#1436]
Hi!! first of all a very big fan of Blynk.  Been using it for a long time to perform hobby projects.
Recently i received a mail from google regarding third party apps after may 2022. How do i allow local blynk server to send email to other clients.

Sorry if i have missed anything. Just a newbie.

**Comment by mikekgr** [comment]
Same here.
Please Blynk, show us the way! Thanks

**Comment by mikekgr** [comment]
Dear All,
as of May 30, 2022, ​​Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password, so there is big problem with the email sending of local Blynk server.
Is there any workaround or something that we can do?
Please help us !
Thanks and Best Regards

**Comment by jason1987martis** [comment]
There is a work around for this problem. You have to use app passwords in Google for javax authentication. I.e. instead of mentioning your password in the javax package use the app password provided by Google. 
Every account of Google has app password. Just follow the simple instructions set forward by Google in terms of your account settings and you're done.
