### ISSUE TITLE
Documentation is of poor quality, Users confused and requesting better

### ISSUE THREAD

**Issue by jamieisboss** [blynkkk/blynk-server#172]
e.g. http://community.blynk.cc/t/local-blynk-server-tutorial/5302/13

To be fair, the simple setup doesn't explain anything and running the server from a downloads folder (unless iv'e  misunderstood as i haven't installed the server yet) is not a good idea, the advanced setup doesn't actually have any instructions for many of the points, just lists of the variables to change

SSL is much easier now and should be updated to use [letsencrypt](https://letsencrypt.org/getting-started/)

Standardisation of installations could be achieved with an install script, taking into account the "advanced" setup, which IMHO should be the standard, a script (two really: a windows and a bash script) could easily generate the settings file and reduce the setup complexity considerably.

I'll happily start on a script or on some wiki pages here if no-one has a preference I'll start with a basic install wiki to let people get an install going ASAP, Moving on to a bash script after, including letsencrypt, 

I dont have a windows machine so could do with help for that, once install scripts were done,  documentation would be much much simpler

Also might be worth mentioning that someone is  maintaining a docker repo: 

https://github.com/mpherg/blynk-server 

which would be the easiest method for some people

**Comment by doom369** [comment]
Hello. Yes, documentation is not the best. But this is mostly due to lack of time. You are welcome to contribute.

> SSL is much easier now and should be updated to use letsencrypt

Did you personally try to use it? I did and must say it is very complex. For 99% of Blynk users it will be impossible due to complexity. SSL itself is hard thing.

> Standardisation of installations could be achieved with an install script, taking into account the "advanced" setup, which IMHO should be the standard, a script (two really: a windows and a bash script) could easily generate the settings file and reduce the setup complexity considerably.

Agree.

> I'll happily start on a script or on some wiki pages here if no-one has a preference I'll start with a basic install wiki to let people get an install going ASAP, Moving on to a bash script after, including letsencrypt,

Would be cool.

**Comment by doom369** [comment]
@jamieisboss added Let's Encrypt instruction https://github.com/blynkkk/blynk-server#generate-lets-encrypt-ssltls-certificates
