### ISSUE TITLE
Link in the shared Cloned Project QR is not working

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-server#174]
Touch the QR icon and point the camera to the code below or open the link below - http://tinyurl.com/jd45q3n

**Comment by doom369** [comment]
@vshymanskyy we just discussed that in chat, right?

**Comment by vshymanskyy** [comment]
Exactly

**Comment by doom369** [comment]
So, close?

**Comment by vshymanskyy** [comment]
It would be better to make the message more clear or redirect to
exllanation page if clicked on PC.

**Comment by doom369** [comment]
Ok. But link generated on Android :). Anyway this feature use only 1% of users. So we may ignore this.

**Comment by vshymanskyy** [comment]
http://community.blynk.cc/t/connect-your-existing-rf-devices-to-the-internet-with-blynk/5925/12

**Comment by doom369** [comment]
@vshymanskyy this is Andorid issue.
