### ISSUE TITLE
Provide Let's Encrypt SSL/TLS Certificates for websockets and hw ssl ports

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-server#209]

**Comment by pinya** [comment]
I think that you can do it yourself

First install `certbot` on your server

```
wget https://dl.eff.org/certbot-auto
chmod a+x certbot-auto
```
And generate certs:

`./certbot-auto certonly --standalone --email your@email.com -d yourdomain.com`

Add password to you let's encrypt certificate and reformat it:

```
mkdir /srv/blynk-data
cp /etc/letsencrypt/live/yourdomain.com/fullchain.pem /srv/blynk-data
cp /etc/letsencrypt/live/yourdomain.com/privkey.pem /srv/blynk-data

cd /srv/blynk-data
openssl pkcs8 -topk8 -inform PEM -outform PEM -in privkey.pem -out privkey_pass.pem
```

Then add to your `server.properties` file (in folder with server.jar)

```
server.ssl.cert=/srv/blynk-data/fullchain.pem
server.ssl.key=/srv/blynk-data/privkey_pass.pem
server.ssl.key.pass=your_password
```

**Comment by pinya** [comment]
I think that each user should generate certs itself. Maybe some instructions should be good first step?

First install `certbot` on your server
```
wget https://dl.eff.org/certbot-auto
chmod a+x certbot-auto
```
And generate certs:
```
./certbot-auto certonly --standalone --email your@email.com -d yourdomain.com
```
Add password to you let's encrypt certificate and reformat it:
```
mkdir /srv/blynk-data
cp /etc/letsencrypt/live/yourdomain.com/fullchain.pem /srv/blynk-data
cp /etc/letsencrypt/live/yourdomain.com/privkey.pem /srv/blynk-data
cd /srv/blynk-data
openssl pkcs8 -topk8 -inform PEM -outform PEM -in privkey.pem -out privkey_pass.pem
```
Then add to your server.properties file (in folder with server.jar)
```
server.ssl.cert=/srv/blynk-data/fullchain.pem
server.ssl.key=/srv/blynk-data/privkey_pass.pem
server.ssl.key.pass=your_password
```

**Comment by doom369** [comment]
@pinya nice! thank you!

**Comment by doom369** [comment]
Instruction is here https://github.com/blynkkk/blynk-server#generate-lets-encrypt-ssltls-certificates
