### ISSUE TITLE
After delete some widgets they stay "Installed" in widgets menu

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#215]
1)add widget(Twitter, push, e-mail, tabs, bridge or rtc)
2)delete this widget
3)open widgets menu
Result: under of widget title is label "installed"
P.S. New widget can't add

**Comment by doom369** [comment]
@Refenz is that server issue?

**Comment by Refenz** [comment]
@doom369 the server has been changed, by the logic in it a reason
P.S. maybe server not send a request answer, move to android?

**Comment by doom369** [comment]
> move to android
Yes, please.

> the server has been changed, by the logic in it a reason

This part was unchanged.
