### ISSUE TITLE
LCD generates "HIGH" on analog pin

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#230]
1)Add LCD(simple mode, pin0=Analog, pin1=Virtual, use /pin0/ and /pin1/)
2)Run project
you see like next:
![44](https://cloud.githubusercontent.com/assets/16590099/15948985/da77342a-2eac-11e6-9714-c6f0d917721f.PNG)
3)Perform PUT "  http://qa.blynk.cc/TOKEN/pin/VirtualPIN  " with any value (   ["100"]   )
you see next:
![55](https://cloud.githubusercontent.com/assets/16590099/15949077/6aeaa820-2ead-11e6-963a-b7426f5e6637.PNG)
Result: now analog pin every time is "HIGH"

**Comment by doom369** [comment]
@Refenz there was one more bug - LCD value wasn't updated via HTTP PUT in realtime on application. Also fixed. Please verify on QA.
