### ISSUE TITLE
Send Hardware connected message on Dashboard activation

### ISSUE THREAD

**Issue by aashvetsov** [blynkkk/blynk-server#232]
Send Hardware connected message on Dashboard activation

**Comment by doom369** [comment]
@aashvetsov please provide use case scenario.

**Comment by aashvetsov** [comment]
No required any more. I'll use http api which is already implemented (on we use in provisioning)

**Comment by doom369** [comment]
@aashvetsov indeed right now server supports HARDWARE_CONNECTED (code = 4) command. It is send to application when hardware successfully logins. However it is not related with "Activate".

**Comment by aashvetsov** [comment]
@doom369 Ok thanks - will check it.
