### ISSUE TITLE
zeRGBa merges value

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#233]
1)use zeRGBa in Merge mode
2)do GET
Result: ["25500", "25500", "25500"]
Expected result: ["255", "0", "0"]

**Comment by doom369** [comment]
@Refenz could ypu please check this case for all multipin widgets?

**Comment by doom369** [comment]
@Refenz fixed on QA. Verify all other multi pin widget and create separate tickets if issue reproducible for them.
