### ISSUE TITLE
LCD sends incorrect first string

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#235]
1)add LCD(use Advanced mode)   
2)use in sketch next string:
```
 lcd.print(0,0, "  Garage Door");
 lcd.print(5, 1, "Closed");
```
3)use GET in API
Result:` ["p51Closed","p51Closed"]`
Expected result:` ["p00Garage Door","p51Closed"]`
P.S. I must see string position in request ("p51")?

**Comment by doom369** [comment]
@Refenz This is how LCD works. Efforts for fixing this are pretty large, so we leave it as known issue.
