### ISSUE TITLE
Generate QR for project via HTTP API

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#236]

**Comment by pieman64** [comment]
Thanks for adding this issue to Blynk's github.

Regards
Costas

**Comment by doom369** [comment]
@pieman64 sorry for delay, was partying hard :). We will do new deployment soon, so QR via web will be available soon.

With url 
`http://blynk-cloud.com/TOKEN/qr`

**Comment by pieman64** [comment]
Glad you enjoyed your visit and thank you friend for the multiple temperature probes suggestion.
Working model at https://www.youtube.com/watch?v=9dx39k2YxfI

**Comment by pieman64** [comment]
@doom369 I believe your server is now running version 0.16.3 but when I try http://blynk-cloud.com/TOKEN/qr (with an actual token) nothing happens.

Costas

**Comment by doom369** [comment]
Not yet deployed. We plan to release 0.16.4 and deploy with it.
