### ISSUE TITLE
Make LCD remember entire LCD display on App re-open (not just the Last "sent" values)

### ISSUE THREAD

**Issue by Phoenix260** [blynkkk/blynk-server#239]
if doing something like:

LCD.print(0, 0, "Hello");
LCD.print(0, 1, "World");

only "World" will be displayed on the bottom line if the app was closed while sending this data, but opened after some time has passed since sending both commands ... Both should be displayed.

**Comment by doom369** [comment]
@Phoenix260 will be available in 0.17.1. If you have local server I can provide you a build.
