### ISSUE TITLE
Pin History data do not match with used value

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#250]
Use Vpin without any data
1)use PUT ["444"]  AuthToken/pin/V31
2)use AuthToken/data/V31
3)open data file
Result: 777.5

**Comment by doom369** [comment]
@Refenz not reproduced. I think you just had old data there. To check pin has no data try to make get request for `data/pin` it should return `Error getting pin data.` that means pin has no data.

**Comment by Refenz** [comment]
@doom369 Yes, i do it before. 
I see "Error getting pin data." and then PUT value "444".
