### ISSUE TITLE
[Feature Request]Using Xbox 360 controller for desktop client

### ISSUE THREAD

**Issue by Addicted5** [blynkkk/blynk-server#257]
Hi,blynk can be used in various IOT projects.
All are controlled from mobile app or desktop app (client.jar)
But in some cases like controlling RC ,using a Xbox (or similar game controller ) seems better option.
It would be a nice addition to blynk app .(Is there any alternative already supporting bot/RC from XBOX???)

**Comment by doom369** [comment]
Didn't see anything like that.

**Comment by doom369** [comment]
I recommend you to post on http://community.blynk.cc maybe someone already did that.
