### ISSUE TITLE
Add support for inserting custom date point

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#258]

**Comment by doom369** [comment]
@vshymanskyy please remind me what this feature if for?

**Comment by doom369** [comment]
PUT with body `{"value":"1", "timestamp":234234234}`
URL : `{token}/pin/extra/{pin}`

**Comment by vshymanskyy** [comment]
Please also add ability to insert multiple points with one request. This is crucial for this feature.
I think this could be done as 2 arrays of timestamps and data points, to make request size a bit smaller.

**Comment by doom369** [comment]
@vshymanskyy 

`[{"value":"1", "timestamp":234234234}]`

Please tell what this feature is for.
