### ISSUE TITLE
 rest api doesn't work when application channel disconnected

### ISSUE THREAD

**Issue by aaddame** [blynkkk/blynk-server#261]
I have an android app with a button that drives a virtual pin on a particle photon.
If the app channel is registered , rest api works as expected. But a s soon as the app channel disconnects, nothing will be sent to the photon.

**Comment by doom369** [comment]
Hello. Do you use local server or Blynk Cloud?

**Comment by aaddame** [comment]
Sorry for opening this. User error. Working now.
