### ISSUE TITLE
Simpler HTTP API for PUT

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#295]

**Comment by doom369** [comment]
@igaidai4uk we need to simplify write/update HTTP API. See current implementation - http://docs.blynkapi.apiary.io/#reference/0/pin-actions/write-pin-value.

For many users update via POST/PUT request is hard. We need to make update via GET request.
Instead of 
`PUT http://blynk-cloud.com/auth_token/pin/pin`
and body
`[ "1"]`

Should be (in addition) : 

`GET http://blynk-cloud.com/auth_token/update/pin?value=1`

for multipins : 

`GET http://blynk-cloud.com/auth_token/update/pin?value=1&value=2`

**Comment by aikar** [comment]
@doom369  Note, while I see the new one is live, the old method was broken even before going live as it throws a 500 error, and is still broken.

For backwards compat, would be good to support both for a time.

**Comment by doom369** [comment]
@aikar old methods are there and weren't changed. Could you please provide more info. What type of query and body?

**Comment by aikar** [comment]
@doom369 exactly as you wrote above, using curl with -X PUT -d '["1"]' http://blynk-cloud.com/token/pin/V1

I'm receiving a 500 code. If you check access logs, should be there from shortly before I replied as I re-tested.

**Comment by doom369** [comment]
@aikar you didn't provide `Content-Type` header. It is a must. 

`-H "Content-Type: application/json"`
