### ISSUE TITLE
Handle table commands on server side

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#297]

**Comment by vshymanskyy** [comment]
Does this cause Table widget to interfere with sync feature?

**Comment by doom369** [comment]
Partially. Sync not yet implemented for table.

**Comment by doom369** [comment]
@vshymanskyy and to be honest I'm not sure I know how it should work with hardwar. Wouldn't it be too much for hardware to sync 100 rows?

**Comment by vshymanskyy** [comment]
It would be a little tricky to avoid floods...
