### ISSUE TITLE
No energy requirement for people self-hosting.

### ISSUE THREAD

**Issue by tenten8401** [blynkkk/blynk-server#336]
I think this should be something like how Nylas N1 (Email Client) works. You can use the free, hosted server for your things, and you have to pay. However, hosting your own server would remove this restriction and you could put as many blocks as you possibly want in your "app". Anyone here agree with me?

**Comment by doom369** [comment]
@tenten8401 agree and it is already done. Just open admin page of local blynk server.

**Comment by tenten8401** [comment]
I feel like a complete idiot now. Didn't notice that, thanks!

**Comment by doom369** [comment]
Not a problem. It is not described anywhere :).
