### ISSUE TITLE
Server 0.19.0 Fails to parse server.properties

### ISSUE THREAD

**Issue by audiohacked** [blynkkk/blynk-server#351]
ERROR - Error parsing file '/home/pi/Blynk/server.properies'. Error : Unrecognized token 'allowed' : was expecting ('true', 'false', or 'null') at [Source: /home/pi/Blynk/server.properties; line: 1, column: 9]

**Comment by doom369** [comment]
Hello. Please show your `server.properties`.

**Comment by audiohacked** [comment]
```
allowed.administrator.ips=
file.folder=/home/pi/Blynk
logs.folder=/home/pi/Blynk/logs
```

**Comment by doom369** [comment]
Please attach full file.

**Comment by audiohacked** [comment]
[server.properties.txt](https://github.com/blynkkk/blynk-server/files/546087/server.properties.txt)

**Comment by doom369** [comment]
@audiohacked sorry for delay. Missed your comment. Issue not reproducible. Few things - why your file has ending `.txt`? Do you specify path to config?

**Comment by audiohacked** [comment]
The file ends in ".txt" because Github won't accept any files other than plain text or images.

**Comment by audiohacked** [comment]
I don't understand how the file is unable to be parsed in version 0.19.0, when the file worked just fine in version 0.18.1!

**Comment by doom369** [comment]
@audiohacked ok. I know the problem. You are using data folder that contains server.properties. Solution would be to move server.properties from data folder.

**Comment by doom369** [comment]
@audiohacked I also added filter, so in next versions this error will be gone.
