### ISSUE TITLE
Collect data about hardware

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-server#397]
It would be good to collect a table with info about hardware, to diagnose real-life usage and stability:

* Account info
  * auth token
  * device name
  * device created timestamp
  * project name
  * account email
  * device type, as selected in app
* Hardware info header
  * library version (*ver* tag)
  * device type (*dev* tag)
  * conection type (*con* tag)
  * cpu info (*cpu* tag)
  * heartbeat (*h-beat* tag)
  * build date (*build* tag)
* Statistics
  * info about current session (if connected), previous session, longest session, and all sessions total (for \*):
    * device ip address
    * was it secure (SSL)?
    * session start timestamp (\* - first session timestamp)
    * session duration (\* - total onlune time)
    * received/transmitted message count (\*)
    * received/transmitted bytes count (\*)
    * received/transmitted biggest command size, except login/info messages (\*)
  * additional
    * longest offline duration
    * total count of sessions
    * maximum amount of parallel sessions with same auth
    * count disconnects because of flood

**Comment by vshymanskyy** [comment]
structured for easier implementation

**Comment by doom369** [comment]
Partially done in the new Blynk Platform.
