### ISSUE TITLE
hw command to push hardware-features

### ISSUE THREAD

**Issue by erazor83** [blynkkk/blynk-server#41]
I hope this is the right place to put in some ideas.

I've just started with the blynk protocol and was wondering if there should be a command for the hardware to push it's features. Features would be the number of analog in/outputs and/or digital in/outputs.

As far as I've seen, there are some standard json configs for known hardware.

**Comment by doom369** [comment]
Hardware features are handled on application side. In order to add new hardware to the [list](https://github.com/blynkkk/blynk-library/tree/master/boards_json) please create ticket in https://github.com/blynkkk/blynk-library

**Comment by doom369** [comment]
Or you mean "how to setup PIN MODES for hardware?"

**Comment by erazor83** [comment]
No, i was just thinking what happens if users build their own virtual hardware via node.js / python or whatever. It wouldn't make sense to submit these globally since it's user dependent. Also users might build their own hardware with different functions.

Submitting and integrating these into the service via tickets would consume a lot of time and you end up with tons of board descriptions.

Having some kind of service functionality shouldn't be that difficult?

I think there have to be 2 functions at least:
  * when user creates a project / creates token: server asks for hardware setup
  * hardware can push it's functions to server

The data would be some kind of a dictionary/array like this:
label: "My custom board",
manufacturer: "me and myself",
```
ios: {
  digital: {
    pin0: {
      label: 'Pin0'
    }
  },
  analog:
...
}
```

**Comment by doom369** [comment]
Exactly for that case we have "Generic Board".
