### ISSUE TITLE
QA. Board every time disconnected.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#417]
After connect board to Internet:
![device-2016-12-30-234045](https://cloud.githubusercontent.com/assets/16590099/21573125/9d81500e-cee9-11e6-8e2c-8b85454cf2b8.png)
and wait few seconds:
![device-2016-12-30-234102](https://cloud.githubusercontent.com/assets/16590099/21573133/aa269da0-cee9-11e6-8f88-9e9f8155ce1f.png)
Another Project and Account the same.

**Comment by doom369** [comment]
@Refenz steps, details?

**Comment by Refenz** [comment]
@doom369 
1)Flash sketch
2)Start project and open device status (offline)
3)Connect via USB (blynk-ser.bat)
4)Device status changed to "online" (but widget doesn't work)
5)Wait few seconds 
6)Device status changed to "offline"

**Comment by doom369** [comment]
@Refenz what blynk debug on hardware shows?

**Comment by Refenz** [comment]
@doom369 
Can't use monitor port in Arduino IDE.
Port is busy when board connected to Internet.

**Comment by doom369** [comment]
@Refenz please verify on QA.

**Comment by Refenz** [comment]
@doom369 
Still reproduced.

**Comment by doom369** [comment]
@Refenz deployed new build with possible fix. Please check again.

**Comment by Refenz** [comment]
@doom369 
The same.
But app shows status "offline" all the time (and when GET /isHardwareConnected is "true")

**Comment by doom369** [comment]
@Refenz I can't reproduce. Tried many different cases. I need very detailed step from you. Can you install local server and enable `trace` level of logging?

**Comment by doom369** [comment]
@Refenz here is latest build https://github.com/blynkkk/blynk-server/releases/download/v0.21.2/server-0.21.3-SNAPSHOT.jar

**Comment by Refenz** [comment]
@doom369 
[blynklog.txt](https://github.com/blynkkk/blynk-server/files/682055/blynklog.txt)

**Comment by Refenz** [comment]
@doom369 
Create new account: a@mail.ru
[logApp.txt](https://github.com/blynkkk/blynk-server/files/682089/logApp.txt)
[blynklog2.txt](https://github.com/blynkkk/blynk-server/files/682090/blynklog2.txt)

**Comment by doom369** [comment]
@Refenz seems like hardware issue according to logs.
