### ISSUE TITLE
server.property does not have options to define locations of sms.property and mail.property

### ISSUE THREAD

**Issue by trombik** [blynkkk/blynk-server#418]
Most, if not all, of distributions needs a directory where all the configuration files reside, typically `/etc/blynk/`. The `blynk-server` has an option to specify `server.property` but others are hard-coded, forcing users to keep them in the same directory of the Java binary.

It would be nice for `server.property` to support these paths.

**Comment by doom369** [comment]
Done via `-mailConfig` and `-smsConfig` properties. See https://github.com/blynkkk/blynk-server#advanced-local-server-setup for more details.
