### ISSUE TITLE
The application does not write its PID file at startup

### ISSUE THREAD

**Issue by trombik** [blynkkk/blynk-server#419]
Although it might be specific to Unix platforms, writing a PID file at start up is a common requirement in Unix platforms. Without it, a wrapper program has to handle the PID file at start up, such as `daemon(8)` in FreeBSD or `start-stop-daemon` in some Linux distributions.

The startup routine should create a PID file at startup and the location of it should be configurable.

**Comment by doom369** [comment]
@trombik and it shouldn't as this is envirnoment specific. You can easily achieve it with on Linux-like systems with 

`java -jar server.jar & echo $! > pid.file`
