### ISSUE TITLE
Status issue

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#420]
http://community.blynk.cc/t/device-is-disconnected-but-not-really/10312

**Comment by Refenz** [comment]
@doom369 
Probably the same: https://github.com/blynkkk/blynk-server/issues/417

**Comment by doom369** [comment]
Do you have multiple devices?

**Comment by Refenz** [comment]
@doom369 
No. But have it in project before. (  j@mail.ru  QA)
Trouble starts from 30/12/2016.
With QA and Prod too.
Board connected to the server and then disconnected.

**Comment by doom369** [comment]
@Refenz please enable android log and attach to ticket.

**Comment by Refenz** [comment]
@doom369 
[logOffline.txt](https://github.com/blynkkk/blynk-server/files/680881/logOffline.txt)
1)Start project
2)Open device status(show Offline)
3)Connect board to Network
4)Status Online
5)Status Offline
