### ISSUE TITLE
ESP8266 server-side OTA manager

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-server#446]
https://github.com/blynkkk/blynk-library/blob/master/examples/Export_Demo/Template_ESP8266/ota-server.js

https://github.com/blynkkk/blynk-library/blob/master/examples/Export_Demo/Template_ESP8266/OTA.h

Here is a working implementation of OTA for ESP8266. Currently it uses hardcoded pin V100.
We can add an internal command to trigger OTA and pass parameters.

**Comment by Refenz** [comment]
@doom369 
There is a need to implement this functionality ASAP.

**Comment by Refenz** [comment]
@doom369 
Is there an estimate on this issue?
The waiting period is 1 week, this is the maximum.

**Comment by doom369** [comment]
@Refenz 1 day for server side.

**Comment by doom369** [comment]
https://github.com/blynkkk/blynk-library/issues/356

**Comment by doom369** [comment]
@vshymanskyy basic version is done. I'll create separate tickets for other improvements in future.
