### ISSUE TITLE
Change RTC workflow with "info" command

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#447]

**Comment by vshymanskyy** [comment]
info is renamed to internal. variants:
ver|....
app|conn
app|disc
rtc|sync
rtc|<unix time>

**Comment by vshymanskyy** [comment]
Need one more change, as I shortened commands to single word (really makes sketches smaller):
acon
adis

**Comment by doom369** [comment]
Ok. I have separate ticket for that. As this is a bit different features.
