### ISSUE TITLE
AUTH-token refreshes without user participate.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#467]
https://github.com/blynkkk/blynk-ios/issues/601 and https://github.com/blynkkk/blynk-ios/issues/600 possibly associated with this.

After QR-scan copy and original project have the same AUTH-token.
Probably server refresh it both(must refresh only copy). After that original AUTH-token is: `Invalid token.`

Have two invalid AUTH-token(before they work 100%):

First see this bug here:  45.55.96.146    d63c24d3645a49bfbdd1151f4f242f4d (bigfogg2017@****)
QR from QA
and could second reproduce:  QA   46811902c605440d961983b617f3f33a (j@*****)
QR from QA

100% steps to reproduce have not found.
1)Create project
2)Open project settings and press "Clone"(project QR open to scan)
3)Take iOS device and scan QR from second device.
4)Open Project settings of new project
5)Take AUTH and use GET
6)Result: `Invalid token.`
7)Return to original project
8)Try GET
9)Result: `Invalid token.`(before work fine)

Close if it will not be investigated.
Corner case.
P.S. Many times the project settings have been updated and all the time he showed the old  AUTH-token (in first case with 45.55.96.146). Only the next day he updated.

**Comment by doom369** [comment]
@Refenz I think this is iOS issue and token is cached during cloning.

**Comment by Refenz** [comment]
@doom369 
Why original token ceases to be valid?

**Comment by doom369** [comment]
@Refenz this server bug and apps bug as well. I'll fix it on server for now.

**Comment by doom369** [comment]
@Refenz I did a fix and deployed on QA. Please make also tickets for iOS and Android - "During cloning devices shouldn't clone auth tokens".

**Comment by doom369** [comment]
@Refenz please reopen if reproduced.
