### ISSUE TITLE
unable to access server

### ISSUE THREAD

**Issue by muthu1995** [blynkkk/blynk-server#468]
![1](https://cloud.githubusercontent.com/assets/25364523/22328915/bb21d600-e3e4-11e6-8503-19a1eeb50821.PNG)

please take a look at that pic ..I'm unable to access the server I don't know what mistake i made

**Comment by doom369** [comment]
@muthu1995 probably because it is in another folder?

**Comment by muthu1995** [comment]
@doom369 Sir, can you please help me with " how to find in which folder is jar"?

**Comment by doom369** [comment]
You need either specify full path to jar or run java from folder where jar file is located.

**Comment by muthu1995** [comment]
![2](https://cloud.githubusercontent.com/assets/25364523/22330579/f1c19ae4-e3ec-11e6-9251-31182382976c.PNG)
thanks for your support sir
@doom369 sir, I have my server jar file in that location only and if I post that location it still shows cannot access , am i specifying anything wrongly ..
![3](https://cloud.githubusercontent.com/assets/25364523/22330643/47ad0ac4-e3ed-11e6-8942-83a1e64c6994.PNG)

**Comment by doom369** [comment]
Please try to specify full path to jar. If that doens't help - please try run "cmd" as administrator (right click on cmd shortcut and "Run as Administrator")

**Comment by doom369** [comment]
Closing. In case you still have issue with server - please use http://community.blynk.cc
