### ISSUE TITLE
Bridge functionality issue

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-server#48]
нужно разобраться с бриджом:
у меня ардуина детектит движение и передает на фотон через бридж, который включает ночную подсветку
- ардуино еще выступает клоном пульта проектора
- фотон также мониторит температуру и цветы 
- к каждой железке есть проект в апке

бридж работает через раз. При этом, как мне кажется, все связано с тем, какой проект активный сейчас. 

какими-то танцами с бубном, активацией на ведре/ оси / деактивацией проектто мне удавалось его обмануть и заставить все работать

я бы хотел понимать как мне это сделать нормально?

**Comment by doom369** [comment]
@blynkkk https://github.com/blynkkk/blynk-library/issues/51
