### ISSUE TITLE
QA. Timer doesn't send min-max value.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#482]
1)Add timer
2)Setup Vpin
3)Change min=10 and max=11
4)Start project
5)Use REST: [10]
6)Wait timer activation
AR:  REST: [10]
ER:  REST: [11]

**Comment by doom369** [comment]
@Refenz should be fixed with latest deploy. Please check again

**Comment by doom369** [comment]
@Refenz fixed and deployed. Reopen if reproduced.
