### ISSUE TITLE
Terminal duplicates strings issue

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#487]
http://community.blynk.cc/t/strange-behavior-on-terminal-widget/11643

**Comment by doom369** [comment]
@Refenz please check on QA. Reopen if reproduced.

**Comment by doom369** [comment]
@Refenz few reports that issue is reproduced.

**Comment by Refenz** [comment]
@doom369 
Full log: [logD.txt](https://github.com/blynkkk/blynk-server/files/810536/logD.txt)
Catch it four times.(for exmaple: 19:25:33)
There is no duplication in the log.

**Comment by doom369** [comment]
@Refenz 19:25:33 was printed 2 times?

**Comment by Refenz** [comment]
@doom369 
In app(terminal widget), yes.
In log, no.

**Comment by doom369** [comment]
Seems like app issue.

**Comment by WoodyKu** [comment]
This duplication in terminal widget still exists in latest releases of Blynk app, library and widget. Is there another issue number that tracks it?

**Comment by doom369** [comment]
@WoodyKu iOS?

**Comment by WoodyKu** [comment]
Yes, iOS.

**Comment by doom369** [comment]
@WoodyKu for iOS not fixed yet. It will be fixed only since 2.26.0 version.
@eepetrash FYI.
