### ISSUE TITLE
eventor for multiple device

### ISSUE THREAD

**Issue by ErfanDL** [blynkkk/blynk-server#552]
Hi. please add an option to set multiple device in eventor. for example if temp on esp8266 goes to 50 degree then arduino uno pin5 turn on

thanks

**Comment by doom369** [comment]
@ErfanDL hello. we are aware of this request and will be done at some point. Don't worry it is in our roadmap.

**Comment by ErfanDL** [comment]
@doom369 thanks for reply. Can you tell me when ? because I need planning for my big project
thanks

**Comment by doom369** [comment]
Bo estimates. Sorry.

**Comment by ErfanDL** [comment]
@doom369 Hi. is any planning for this feature ? :(
thanks

**Comment by ErfanDL** [comment]
@doom369 Im waiting for this feature :(

**Comment by doom369** [comment]
@ErfanDL sorry, at the moment we are busy with other tasks.

**Comment by ErfanDL** [comment]
@doom369 but this feature is very important !!! :((

**Comment by doom369** [comment]
@jpcwilliams no news right now. However, we are very close to start work over it.

**Comment by Vampir8** [comment]
What stage are the works at?

**Comment by doom369** [comment]
This will be a part of Blynk 2.0 and already implemented.

**Comment by uszol90** [comment]
I can not wait for the new version of Blynk, when you plan to share ver. 2.0?

**Comment by doom369** [comment]
The planned date of the release is the end of May. Yes, it will be web + apps.

**Comment by rikvandersteen** [comment]
Hello is still the release date planned  end of May        for support multiple event devices at same time

**Comment by rikvandersteen** [comment]
hello is the planning still end of may   , and do i need to change my own server or is there also then a update for

**Comment by doom369** [comment]
Hello. It will be part of the new Blynk product.

**Comment by rikvandersteen** [comment]
thank you is still planned for this month   , and is there than a new server build

**Comment by mitriy** [comment]
So, as far as I can see this is still not released. Any updates on this ?

**Comment by doom369** [comment]
Hello. No. It was done as part of the Blynk 2.0, however this version for now only available for paid customers.

**Comment by ben700** [comment]
Any update?
