### ISSUE TITLE
Server should query info from hardware

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-server#56]
Upon connection, server should send info request and read data provided by hardware.
It should take heartbeat value into account, (defaulting to 30 seconds?).
It can also collect info about hardware type.

**Comment by doom369** [comment]
Could you describe command format and response?

**Comment by vshymanskyy** [comment]
currently you send a hardware command "info" and get the response (0-separated key-value pairs).
it might need to be tweaked a bit

**Comment by doom369** [comment]
"you"? server or hardware?

**Comment by vshymanskyy** [comment]
Server sends "info" and then gets a response

**Comment by doom369** [comment]
Implemented for login command.
