### ISSUE TITLE
Skip invalid bytes in the beginning of the stream.

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-server#57]
After incoming connection was accepted, server should try seeking a valid login message.
It may expect to receive up to 50 bytes of invalid data before a valid message.

**Comment by doom369** [comment]
@vshymanskyy I need a reproducer for it. Can't fix without it.

**Comment by doom369** [comment]
@vshymanskyy closing. Can't fix it without real reproducer.
