### ISSUE TITLE
Add timestamp and device name when saving profile

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-server#58]

**Comment by blynkkk** [comment]
Could you be more specific?

**Comment by doom369** [comment]
Closing as not clear what to do here

**Comment by blynkkk** [comment]
Reminder: ticket can be only closed by the person who opened it.

Timestamp will be needed to identify latest saced verson of user's profile. Device name will be also ysed for that

Use cases: offline mode

**Comment by doom369** [comment]
This is done already
