### ISSUE TITLE
Consider move app from 8443 port to 443

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#588]

**Comment by cprosser** [comment]
Please do this. App is unusable when I am at work because non standard ports are blocked. It's a Fortune 500 company and there is zero chance of getting the custom port unblocked.

**Comment by doom369** [comment]
It is not that simple as we have `https` on 443 already :). We'll try anyway.

**Comment by cprosser** [comment]
Yeah, that can make it harder :). You could also move it out the load balancer lever, then all you need is a different endpoint on 443 and have the loadbalancer rewrite and redirect to 8443. Sort of like: https://serverfault.com/questions/650117/serving-multiple-proxy-endpoints-under-location-in-nginx

**Comment by doom369** [comment]
Done as part of #870.

@cprosser FYI. I think in week or two we will deploy it to out public cloud.
