### ISSUE TITLE
Server doesn't change hardware pin state via API.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#604]
1)Open API
2)PUT /pin/D13   ["1"]
AR:
Nothing changes on the hardware
ER:
Hardware board LED turn ON

If press Button with this pin in the project, then board led turn ON/OFF. 
If use API, Button in the project change state, but board led no.

**Comment by Refenz** [comment]
@doom369 
Arduino Nano

**Comment by doom369** [comment]
@Refenz I wasn't able to reproduce. Show me this case at Monday. Also we do not use PUTs for get. Pleae use http://docs.blynkapi.apiary.io/#reference/0/write-pin-value-via-get/write-pin-value-via-get

**Comment by ibtisamasif** [comment]
> 1)Open API
> 2)PUT /pin/D13 ["1"]
> AR:
> Nothing changes on the hardware
> ER:
> Hardware board LED turn ON
> 
> If press Button with this pin in the project, then board led turn ON/OFF.
> If use API, Button in the project change state, but board led no.

you managed to solve this issue ? i encountered the same. i hope i do not need to set port forwarding.

**Comment by doom369** [comment]
@ibtisamasif probably you are using wrong pin index. Check the indexes here - https://github.com/blynkkk/boards
