### ISSUE TITLE
SSL instructions in Doc's don't create a key that the server accepts

### ISSUE THREAD

**Issue by rabarar** [blynkkk/blynk-server#61]
The instructions as-written

```
Generate SSL certificates

Create key

openssl genrsa -out server.key 2048
Create new cert request

openssl req -new -out server.csr -key server.key
Generate self-signed request

openssl x509 -req -days 1825 -in server.csr -signkey server.key -out server.crt
Convert server.key to PKCS#8 private key file in PEM format

openssl pkcs8 -topk8 -inform PEM -outform PEM -in server.key -out server.em
```

generates keys the throw an exception:

```
Exception in thread "main" java.lang.RuntimeException: File does not contain valid private key: /home/robert/src/server.pem
	at cc.blynk.server.core.hardware.ssl.HardwareSSLServer.initSslContext(HardwareSSLServer.java:90)
	at cc.blynk.server.core.hardware.ssl.HardwareSSLServer.initSslContext(HardwareSSLServer.java:69)
	at cc.blynk.server.core.hardware.ssl.HardwareSSLServer.<init>(HardwareSSLServer.java:39)
	at cc.blynk.server.ServerLauncher.<init>(ServerLauncher.java:39)
	at cc.blynk.server.ServerLauncher.main(ServerLauncher.java:63)

```

**Comment by doom369** [comment]
@rabarar I think you made a typo here :

```
-out server.em
```

should be 

```
-out server.pem
```

**Comment by rabarar** [comment]
I believe that was a typo in the issue drafting. It barfs on the pem file being an invalid cert key.

**Comment by doom369** [comment]
Show me please your server.properties file

**Comment by doom369** [comment]
@rabarar was you able to resolve your issue?

**Comment by rabarar** [comment]
No. I'll send you my server.properties file in a few minutes ...

**Comment by rabarar** [comment]
Here's the section of my file that has the ssl config 
```
server.ssl.cert=/home/robert/src/server.crt
server.ssl.key=/home/robert/src/server.pem
server.ssl.key.pass=xxx
client.ssl.cert=
client.ssl.key=
```

**Comment by doom369** [comment]
Please try to generate new cert and key again. Look like somewhere in the middle there was a mistake. Also please make sure you use correct pass.

**Comment by rabarar** [comment]
I created a cert that has no password, perhaps that might be the problem?

**Comment by rabarar** [comment]
a cert with no password is not accepted. Adding a password words. Perhaps a mod to the docs or the source to reflect that condition is in order.

**Comment by doom369** [comment]
Ok. Thank you for reporting. I'll update doc.

**Comment by seurat-atreides** [comment]
Hi *,
I noticed this issue is old and closed but I was having the same problem until I decide to use v1 PBE-SHA1-2DES algorithm for the encrypted private key:
`openssl pkcs8 -topk8 -v1 PBE-SHA1-2DES -in server.key -out server.enc.key`
The use of this older v1 algorithm worked for me!

**Comment by Delilovic** [comment]
> 
> 
> Hi *,
> I noticed this issue is old and closed.
> I'm running blynk-server on buntu 18.04 server with openjdk 8.
> I was having the same problem until I decide to use v1 PBE-SHA1-2DES algorithm for the encrypted private key:
> `openssl pkcs8 -topk8 -v1 PBE-SHA1-2DES -in server.key -out server.enc.key`
> The use of this older v1 algorithm worked for me!
> 
> Please update the doc!

Oh man this is so true, even today! Thank you I just started losing hope but entering your command saved the night.

Please update
