### ISSUE TITLE
Publishing. Need add metadate with Single/Multi Face data.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#610]
1)Create preview app
2)Press "Publishing"
3)Opens email:
![screenshot_2017-05-13-19-09-09-475_com google android gm 1](https://cloud.githubusercontent.com/assets/16590099/26027085/e977e916-380f-11e7-9249-b60d4aff8d7d.png)

**Comment by doom369** [comment]
@Refenz app issue.
