### ISSUE TITLE
Allow multiple devices to be controlled by a single interface

### ISSUE THREAD

**Issue by rabarar** [blynkkk/blynk-server#62]
Rather than making it a one-to-one mapping between an interface and a device, it would be far more useful to allow multiple devices to be controlled by a single interface.

Moreover, if the app ran on an iPad, there would be more real-estate to make more useful UI controllers.

**Comment by doom369** [comment]
>> it would be far more useful to allow multiple devices to be controlled by a single interface.

You could do that already. Just use same token for different devices or use bridge. 

 >> if the app ran on an iPad, there would be more real-estate to make more useful UI controllers.

Agree but at the moment we do not have resources for that.

Also this has nothing to do with server itself. You could post any proposal on our forum - community.blynk.cc

**Comment by rabarar** [comment]
> On Oct 29, 2015, at 7:38 PM, Dmitriy Dumanskiy <notifications@github.com> wrote:
> 
> it would be far more useful to allow multiple devices to be controlled by a single interface.
> 
> You could do that already. Just use same token for different devices or use bridge.
> 

Well that’s sort of true, but if you have multiple instances of the same device that you want to connect to that use the same GPIO, that won’t work - you have to select a different gpio for each instance, no?


> if the app ran on an iPad, there would be more real-estate to make more useful UI controllers.
> 
> Agree but at the moment we do not have resources for that.
> 
> 
Is there any plans on making the iOS app open source too?

**Comment by doom369** [comment]
>> you have to select a different gpio for each instance, no?

Yes. We will fix this some day in future =).

>> Is there any plans on making the iOS app open source too?

No.
