### ISSUE TITLE
Add Faces name for Multi.Faces preview app.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#625]
1)Create Multi.Faces preview app(with 3 projects)
2)Open e-mail(3 new letter with QR-code for each face)
AR:
It is impossible to determine which code is from which face:
![m](https://cloud.githubusercontent.com/assets/16590099/26274699/6f6f8b62-3d58-11e7-8fd2-652d8e78f9d8.PNG)
ER:
Need to add the text with a description of which face the code is attached, something like that:
![s](https://cloud.githubusercontent.com/assets/16590099/26274700/7109ce6a-3d58-11e7-8e2f-7097b6a8b56b.PNG)

**Comment by doom369** [comment]
@Refenz face name is already included in 

`Nice app you made with Blynk for {project_name}!`
