### ISSUE TITLE
SetProperty issue with LED if it uses Device Selector.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#643]
Android:
`led using device selector is not sending set property command from the device on device selector`

1)Add Slider, Device Selector and LED
2)Setup Slider and LED to Device Selector
3)Start project
4)Move Slider
AR:
LED show selected value.
ER:
LED Show selected value and change color between Green-Orange-Red.

P.S. if use target board(not Device Selector) in LED settings, then all is work.

**Comment by doom369** [comment]
@Refenz fixed and deployed on QA. Will work only in "realtime" while app is opened. Closing and reopening app will not save property update due to high efforts.
