### ISSUE TITLE
LCD. Value update occurs a second later than specified by the user

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#653]
1)Add LCD widget
2)Setup Analog pin
3)Use default "Reading Rate" = 1sec
4)Start project
AR:
Values are updated every (1+1) seconds.
P.S. if use Reading Rate=2, the update will be every (2+1) seconds
if use Reading Rate=5, the update will be every (5+1) seconds

**Comment by doom369** [comment]
@Refenz very nice catch. Same as #499
