### ISSUE TITLE
State change error: undefined

### ISSUE THREAD

**Issue by bestpika** [blynkkk/blynk-server#658]
In `/config/list`, I click `mail.properties`.
The top of screen show `State change error: undefined`.

My crontab.
```txt
@reboot java -jar /home/pi/blynk-server/server-0.25.2.jar -serverConfig /home/pi/blynk-server/server.properties -mailConfig /home/pi/blynk-server/mail.properties &
```

My mail.properties.
```txt
mail.smtp.auth=false
mail.smtp.starttls.enable=false
mail.smtp.host=...
mail.smtp.port=25
mail.smtp.username=...
mail.smtp.password=
```

**Comment by doom369** [comment]
@bestpika this is not supported. We are currently developing new UI for the blynk server. So it will be fixed there. For now - please edit properties manually before starting the server.

**Comment by bestpika** [comment]
Ok, I will edit it manually.

**Comment by MichaIng** [comment]
@doom369 
Is this still current? I get the same error on trying to access web ui `Config` page.

Browser console shows:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error): admin/config?_page=1&_perPage=30&_sortDir=DESC&_sortField=id
Object
- config: {method: "GET", transformRequest: Array(1), transformResponse: Array(1), params: {…}, headers: {…}, …}
- data: ""
- headers: ƒ (n)
  status: 500
  statusText: "Internal Server Error"
- __proto__: Object
(anonymous) @ ng-admin.min.js:23
```

Blynk log shows:

`ERROR- Error invoking handler. Reason : Can't find field id for cc.blynk.server.admin.http.logic.ConfigsLogic$Config`

**Comment by pruchai** [comment]
I get the same error trying to access Config page. Running latest 0.30-1 , but it was happening with earlier versions too

**Comment by doom369** [comment]
Please read my comments above.
