### ISSUE TITLE
 Send the project immediately if the application uses 1 Face with Blynk.Faces (without QR-code scanning)

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#677]
1)Create Preview App 
use only 1 project
use Blynk.Faces
use Dynamic provisioning(optional)
2)Start Preview App
AR:
The application asks you to scan the QR-code.
ER:
The application displays the project. Device firmware is implemented using dynamic provisioning.

P.S. Close if won't fix.

**Comment by doom369** [comment]
No time for that right now.
