### ISSUE TITLE
GPS trigger is not respond.

### ISSUE THREAD

**Issue by uhlmul** [blynkkk/blynk-server#686]
I have a trigger GPS connected to the pin D0 on a nodeMcu board (esp8266), I defined the GPS area should monitor and have conducted tests in and out of the area, the pin D0 on a nodeMcu board does not change state (in NODEMCU pin D0 is connected to an LED). I tried to connect the D0 pin a button and it works. The application is running on a mobile android sony z2. All this running on a local server server-0. 25. 3. jar.

**Comment by doom369** [comment]
@uhlmul hello. Could you please post this to https://community.blynk.cc with code attached? It doesn't related tothe  Blynk Server itself probably.
