### ISSUE TITLE
If re-scan the QR-code from one account, the welcome screen appears.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#692]
1)Login
2)Scan QR-code with new energy
3)Take energy
4)Open QR-scanner again
5)Scan the same QR-code
AR:
The welcome screen appeared, but after pressing "Get 25,000 energy", energy is not added.
ER:
Return fail. App should show that this QR-code was used.

**Comment by Refenz** [comment]
@doom369 
https://github.com/blynkkk/blynk-android/issues/2436

**Comment by doom369** [comment]
@Refenz seems like app issue to me.
