### ISSUE TITLE
Add buffer size check when sending commands to hw

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-server#694]
When server receives "buff in" info from HW (INFO is usually sent after login), it should take it into account.
https://community.blynk.cc/t/solved-timer-widget-fails-to-trigger-every-so-often-with-esp32/16040/28
The action would be to drop the command & possibly notify the user.

**Comment by vshymanskyy** [comment]
Replaces #682

**Comment by doom369** [comment]
@vshymanskyy do you think this is worth it? Actually user could find the issue by himself. All he need to do is enable debug on hardware side.

**Comment by doom369** [comment]
Moving to backlog for now.

**Comment by vshymanskyy** [comment]
Please give hight priority for this - it seems an easy solution + necessary to avoid strange bugs with days of investigation
