### ISSUE TITLE
Can't scan the QR-code in Preview app on the customer server.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#702]
1)Open the application Blynk
2)Log in to the customer's server
3)Open the "My Apps" section
4)Open the application
5)Open the preview app settings
6)Open projects section (Blynk.Feces)
7)Send the QR-code
8)Launch the Preview App
9)Scan the received QR-code
AR:
![screenshot_2017-08-12-00-24-17-705_cc blynk 1](https://user-images.githubusercontent.com/16590099/29232615-373758fe-7ef5-11e7-9652-c9aeec34f64a.png)

**Comment by doom369** [comment]
@Refenz seems like Android issue.

**Comment by doom369** [comment]
> 1)Open the application Blynk

Shouldn't it be client application and not Blynk application?

**Comment by Refenz** [comment]
@doom369 
Not necessary.
This is a basic flow for blynk-server, but it does not work on the customer's server.
The customer must be able to access the preview application on his server.

**Comment by Refenz** [comment]
@doom369 
The same with QA.
Preview Application uses Blynk.Faces and consists of the 1 project.
After launching the Preview, the QR-code scanner indicates the not valid QR-code.

**Comment by Refenz** [comment]
@doom369 
Ping

**Comment by doom369** [comment]
@Refenz is that reproduced right now on coolbot server?

**Comment by Refenz** [comment]
@doom369 
Yes.
Last app version.

**Comment by alexkipar** [comment]
@Refenz app from google play or app from git ?

**Comment by Refenz** [comment]
@alexkipar 
Git

**Comment by doom369** [comment]
@Refenz deployed fix to client. Please verify.
