### ISSUE TITLE
User edit is not autofill-friendly

### ISSUE THREAD

**Issue by ReDetection** [blynkkk/blynk-server#704]
You are probably familiar with password autofill feature in modern browsers. At the moment if you open user edit in Safari, you get user email and password autofilled with saved values, which in my case was the admin email and password. So as I paid no attention to it, when I saved, I believe I got my admin user overwritten by the user profile. So the app could not connect anymore and I had administrator interface problems. 

So the issue is: please make these fields to avoid autofill, maybe to make it readonly until focused.

To be honest, it was easy to get user's profile so the app is working now, but I got admin account screwed and I can not login to administrator console anymore. As a side question: Is there any way to reestablish the admin account without losing users data?

As for the general feedback I like your software very much and recommend to my friends.

**Comment by doom369** [comment]
@ReDetection web interface is just temporary solution. It will be fully replaced soon with modern and cool web.
