### ISSUE TITLE
Implement HW_SYNC command

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-server#71]
Upon connection, hardware may send HW_SYNC command.
Server should reply with a bunch of Hardware commands to update all values.
It would be good for server to push no more then 10 values per second (not to put off the hardware).

**Comment by blynkkk** [comment]
SYNCH? or SYNC ?

**Comment by vshymanskyy** [comment]
Does it matter? It's an identifier )))

**Comment by doom369** [comment]
=)))

**Comment by doom369** [comment]
@vshymanskyy command code - 16. Deployed on QA. tested for button and slider widgets.

**Comment by blynkkk** [comment]
devil is in the details, you know ;)

**Comment by doom369** [comment]
=)))
