### ISSUE TITLE
Notifications don't come to the device when using the customer's server.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#711]
1)Login on the customer's server
2)Open project
3)Run it
4)Send some notification
AR:
No notifications
ER:
Notify message shows.

**Comment by doom369** [comment]
@Refenz more details please. 

`4)Send some notification`

How do you send it? 
What is notification in that case?
What device do you check with?

**Comment by Refenz** [comment]
@doom369 
Android
Blynk app
via API: POST http://customerserver/token/notify
{"body":"123"}

**Comment by doom369** [comment]
Android issue.
