### ISSUE TITLE
Blynk app can't show 1h history.

### ISSUE THREAD

**Issue by bestpika** [blynkkk/blynk-server#716]
I use Blynk server 0.26.2 and install Blynk android app 2.15.0.
In History Graph widget, it can't show 1h data.

**Comment by doom369** [comment]
What do you see in that case on your screen? Do you see some errors in log?

**Comment by bestpika** [comment]
I check device is online.
![image](https://user-images.githubusercontent.com/5698157/29507094-3f66b6bc-8681-11e7-969a-cc1ee3e69893.png)
![image](https://user-images.githubusercontent.com/5698157/29507076-333e622c-8681-11e7-955b-cdb63af19797.png)

**Comment by doom369** [comment]
Do you use local server?
Is there any chance you don't have any data for that period?

**Comment by bestpika** [comment]
@doom369 I'm sure that time have data, because it only 1h can't show data.
When I wait 1 hour, 6h data can show that time data.

**Comment by doom369** [comment]
@bestpika please do CSV export. Do you see data for that period?

**Comment by bestpika** [comment]
I already use ntp to update time.
But I check...BIOS's time is wrong.
I fix it, thank you.
