### ISSUE TITLE
Group OTA

### ISSUE THREAD

**Issue by bestpika** [blynkkk/blynk-server#726]
Could I use ota by group?
Like...
```
curl -v -F file=@Template_ESP8266.ino.nodemcu.bin --insecure -u admin@blynk.cc:admin https://localhost:9443/admin/ota/start?user=user@blynk.cc&project=blynk&tag=weather
```
Thanks.

**Comment by doom369** [comment]
For now you can trigger OTA only for either 1 device (if it is online) or for all devices on the server. OTA for groups is good idea.

**Comment by doom369** [comment]
For now implemented user and project. Hope this will be enough for now.

`curl -v -F file=@Template_ESP8266.ino.nodemcu.bin --insecure -u admin@blynk.cc:admin https://localhost:9443/admin/ota/start?user=user@blynk.cc&project=blynk&tag=weather`
