### ISSUE TITLE
OTA. After downloading the new firmware to the server, the device does not update it on its own.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#730]
1)Connect board
2)Use: curl -v -F file=@Template_ESP8266.ino.bin --insecure -u admin@blynk.cc:admin https://SERVER/admin/ota/start 
3)The firmware was successfully downloaded to the server
AR:
The board is still online, the firmware does not update. It is required in manual mode to reboot the device, that it would update the firmware.
ER:
After downloading the firmware to the server, the device updates it and reboots without the user's help.
P.S. Library issue?

**Comment by doom369** [comment]
Actually this is correct. Firmware update is requested right after connection established with server. This is done to have 1 entry point for firmware update.

**Comment by blynkkk** [comment]
Manual reboot is a bad UX if not communicated properly. There is no chance end-users no that new firmware was uploaded. Also, for remote locations this use case is unacceptable.

Options: 
- ask user to reboot the device in cases where users need to take decision (for example constant monitoring, they need to know that device will be stopped)
- automatically reboot device for devices that are installed remotely (fields, industrial stuff, etc)

**Comment by doom369** [comment]
no time for that
