### ISSUE TITLE
TimeInput. Server doesn't send data to the board.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#737]
1)Add Time Input
2)Use "AdvancedTimeInput" sketch
3)Start project
4)Setup some time
5)Press "Ok" to confirm
AR:
Serial monitor is empty.
The board does not receive this data

App sends a new set time (confirmed by the log).
Server contains changes(GET /project)

ER:
Port monitor contains the information about the changed time in the Time Input widget.

P.S.
blynk-cloud.com

**Comment by doom369** [comment]
@Refenz this code was untouched for very long time. Maybe hardware wasn't online at that moment?

**Comment by Refenz** [comment]
@doom369 
The board (ESP8266) differs from the one with which I tested it earlier (SF BlynkBoard) and it does not send data to the port monitor.
I checked that the widget works correctly, the board gets the necessary data.
