### ISSUE TITLE
Ignored `mail.*` in server.properties 

### ISSUE THREAD

**Issue by amurchick** [blynkkk/blynk-server#75]
I am use `server-0.12.0.jar` on Debian 8.1
```
$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

server.properties
```
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=some_email@gmail.com
mail.smtp.password=some_password

server.ssl.cert=./server.crt
server.ssl.key=./server.pem
server.ssl.key.pass=some-pem-password

data.folder=./bs-data 
```

run
```
java -jar server-0.12.0.jar 
```

blynk.log
```
1:14:52.171 INFO  - Using data dir './bs-data'
11:14:52.800 INFO  - Initializing mail transport. Username : example@gmail.com. SMTP host : smtp.gmail.com:587
11:14:54.629 INFO  - Enabling SSL for application.
11:14:54.631 WARN  - Found server certificates but no client certificate for '/home/bs' path. Using one way ssl.
```

As you see, `Blynk` successfully loads properties `data.folder`, `ssl.params.*` from config, but ignores `mail.smtp.*`

**Comment by doom369** [comment]
@amurchick hello. For mail you have to create separate "mail.properties" files as stated in [doc](https://github.com/blynkkk/blynk-server#enabling-mail-on-local-server). 

> In order to enable mail notifications on Local server you need to provide own mail credentials. To do > that you need to create file "mail.properties" within same folder where server.jar is.
