### ISSUE TITLE
Fix java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#752]
https://community.blynk.cc/t/java-error-on-remote-server-startup/17957/4

**Comment by doom369** [comment]
https://jira.mongodb.org/browse/JAVA-2559

**Comment by hoijui** [comment]
in short: you need Java 9+

**Comment by juice-client** [comment]
thanks
