### ISSUE TITLE
CSV data don't come. The server sends token with a long delay. 

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#767]
1)Start project
2)Open additional settings(Super Chart)
3)Send CSV file
4)Open email
AR:
The file was never received
P.S. tried different projects

**Comment by doom369** [comment]
Sid you check spam folder?

**Comment by Refenz** [comment]
@doom369 
Yes.
Received the data with a delay of 12+ hours.
P.S. Now they are coming up normally, probably because the server was rebooted.

**Comment by doom369** [comment]
@Refenz prod?

**Comment by Refenz** [comment]
@doom369 
QA

**Comment by doom369** [comment]
@Refenz let me know when you again will see the issue.
