### ISSUE TITLE
Change `dispatcher` name to `Blynk` name

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-server#770]
Change  the Name`dispatcher@blynk.io` of  incoming mail address to `Blynk`

Example from mail client shows dispatcher@blynk.io
![image](https://user-images.githubusercontent.com/11541426/32118372-6f23437a-bb1f-11e7-875a-7fdd863a2fa9.png)

**Comment by doom369** [comment]
no.

**Comment by pieman64** [comment]
Dmitriy @doom369 does "no" mean it will not be implemented as "dispatcher" is quite an unpleasant sender name?

**Comment by doom369** [comment]
It is tied to email/account that is used to send emails.

**Comment by pieman64** [comment]
Strange that such a generic term can't be changed but fine if you say that's how it has to be.

**Comment by doom369** [comment]
Let me check.

**Comment by doom369** [comment]
Ok. In general - you can. But for that you have to go trough domain verification procedure with your mail provider.

Much simpler would be just to created required email and use it.

**Comment by doom369** [comment]
@blynkkk I can make it like this:

![screenshot-mail google com 2017-11-01 12-48-02-972](https://user-images.githubusercontent.com/1536494/32271529-fe854d9c-bf02-11e7-8998-3db437a27676.png)

**Comment by pieman64** [comment]
Much better. When?

**Comment by doom369** [comment]
@pieman64 with next deploy. It is just config in `mail.properties`.

`mail.from=Blynk <dispatcher@blynk.io>`
