### ISSUE TITLE
Provide email template for new user registration

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#772]

**Comment by navjotdhanawat** [comment]
@doom369 any update on this?

**Comment by doom369** [comment]
@blynkkk is right person to ask.

**Comment by navjotdhanawat** [comment]
Hi, @blynkkk any update on this?
Currently, I  am working on new user registration but stuck with some issue due to less understanding of java. Can you please tell the status of it?

Thanks.

**Comment by blynkkk** [comment]
Hey there,

Welcome to Blynk, a platform to build your next awesome IOT project.

First of all, make sure to confirm your email address. 
BTN: Confirm Email

**Get Started:**
1. Install Blynk Library. Here is a **step-by-step guide** on how to do that
2. Check ** example sketches** for your hardware  

**Some of Blynk Basics:**
How to read **any sensor** with Blynk app. (for example: DHT11, DHT22, etc)
How to control **any** thing with Blynk app and your hardware (relays, motors, etc)
What is virtual pins and how to use it?
Video: Control Arduino over USB with Blynk app
Video: Control multiple devices with Blynk app (Arduino Mega and nodeMCU)
Video: How to install Local Blynk Server (on your laptop or Raspberry Pi)

If you have questions, post to our [community](http://community.blynk.cc)
Full Blynk documentation is [here](http://docs.blynk.cc).

Enjoy Blynking!

--
Pavel and Blynk Team (можешь поставить тут Dmitiry)
