### ISSUE TITLE
Android and iOS doesn't receive notification on the test server.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#796]
1)application/json
POST http://test.blynk.cc/Token/notify
{"body":"4233"}

Answer:
   ```
    Status Code: 200 OK
    connection: keep-alive
    content-length: 0
```

2)Also, no notifications come when the device is turned off.

Project is launched
Notifications widget present
"Notify when hardware goes offline" On

**Comment by doom369** [comment]
Works for Android. If iOS still reproduces - please create on iOS repo.
