### ISSUE TITLE
Table widget shouldn't have multiple rows with same id

### ISSUE THREAD

**Issue by eepetrash** [blynkkk/blynk-server#797]
AR: After sending the "add" command few times with the same ID, server creates separate rows. This leads to issues when working with rows afterwards.

ER: Server should handle such case and instead of adding a row, just update an existing one. This would also eliminate the need of "update" command, which is inconvenient anyway.

Note: Both clients (iOS and Android) already works as ER above, but gets broken after fetching model from server.

**Comment by doom369** [comment]
@eepetrash fixed. However, such command will be still forwarded to UI.

**Comment by dennymoney** [comment]
Great. Thanks

Denny
