### ISSUE TITLE
Notification Issue

### ISSUE THREAD

**Issue by RadovidV** [blynkkk/blynk-server#807]
Thank you very much for the great effort, I would like to report an issue regarding the notification widget in the blynk android app, it doesn't work when using the blynk local server (tested on version 0.28.9). I'm using Arduino uno+ ESP8266 as a WIFI shield. thanks in advance.

**Comment by doom369** [comment]
@RadovidV please update app to latest one.

**Comment by RadovidV** [comment]
I updated the app to version 2.17.0 with no luck, I can confirm that notifications work perfectly on the cloud server.

**Comment by doom369** [comment]
@RadovidV Issue confirmed. Looking into it.
