### ISSUE TITLE
Superchart Widget Bug

### ISSUE THREAD

**Issue by RadovidV** [blynkkk/blynk-server#808]
When using blynk local server the superchart widget behaves in a weird way, it starts drawing a rippled line which appears and disappears continuously, after like 20 seconds the supercahrt widget draws the data correctly, I'm using (version 0.28.9) although tested on previous versions, the bug remains.

**Comment by doom369** [comment]
@RadovidV could you please video or screens?

**Comment by RadovidV** [comment]
![screenshot_20171207-013401](https://user-images.githubusercontent.com/21297903/33691365-8f9edc5e-daf0-11e7-9e03-0d237517b9be.png)

**Comment by doom369** [comment]
moved to android repo.

**Comment by doom369** [comment]
@RadovidV is issue still there?
