### ISSUE TITLE
Add flag to daemonize blynk process after startup

### ISSUE THREAD

**Issue by paxy97** [blynkkk/blynk-server#810]
I wrote a small systemd unit for blynk, but since the start command blocks and doesn't fork the service times out after a while and kills blynk. I tried adding a `&` at the end of the start command, but as far as I know systemd doesn't use a shell to run it, so it has no effect.

Running it from cron is not that nice, and I like having a lot more control through systemd.

**Comment by doom369** [comment]
This is actually not a Blynk Server issue. Please use https://community.blynk.cc/ for questions or suggestions.

**Comment by paxy97** [comment]
Isn't the point of github issues to also propose new features?

**Comment by doom369** [comment]
Yes, however, this particular issue has nothing to do with Blynk Server itself. It is more about scripting/managing your system.

**Comment by paxy97** [comment]
But I'm asking you to add fork functionality to the blynk server. How is that not a feature request? I configured my system to run blynk on boot, but it doesn't work as it gets killed after a timeout.

**Comment by doom369** [comment]
Could you please explain what do you mean by "fork functionality"?

**Comment by paxy97** [comment]
When you run the blynk server in the shell it claims that shell and blocks you from typing further commands until that server is killed. This can be circumvented by adding an ampersand (&) at the end of the command,  but the server still runs in that shell and as soon as the terminal is closed so is the server.

What I need is a flag for example that tells the server to not run in the shell, but start a separate process. For example if you run nginx in the shell it forks (starts a new process) and you can safely close the shell and it'll keep running.

I need this because systemd (sudo services) doesn't use a shell to run programs and expects them to fork into a new process so that it can continue to run other tasks. The problem is that the blynk server blocks anything else from executing when it started, so systemd kills it after some time as it presumes that it failed to start and fork.

**Comment by teejaydub** [comment]
Forking to the background seems like a very standard thing for server processes to do, so I'm not saying it shouldn't be added - and also not to say you shouldn't be using systemd - but supervisord takes care of this very easily, if that's an option for you in the meantime.

**Comment by paxy97** [comment]
I don't really want yet another management too only for one server. I'd rather launch it with cron then. Systemd is the standard way in most Linux distros and every server should support at least that.

**Comment by doom369** [comment]
@paxy97 sorry, but I still do not understand why this is should be done with Blynk. If you need fork you need to create fork within your system. You probably need to execute something like this to avoid "death" of the process:

`nohup java -jar server.jar &`
