### ISSUE TITLE
reporting_raw_data have no data

### ISSUE THREAD

**Issue by bestpika** [blynkkk/blynk-server#812]
My `server.properties` setting

```
enable.db = true
enable.raw.db.data.store = true
```

But `reporting_raw_data` table have no data.
(other table have data)

![image](https://user-images.githubusercontent.com/5698157/33814837-f834391a-de67-11e7-9568-621fb46a6f97.png)
![image](https://user-images.githubusercontent.com/5698157/33814854-0d9b1ac6-de68-11e7-8385-8931e4e8c55d.png)

**Comment by doom369** [comment]
@bestpika have you enabled DB? What do you see in `postgres.log` file?

**Comment by bestpika** [comment]
Yes, other have new data write.

**Comment by bestpika** [comment]
Can the table record string? line `2017-01-01 00:00:00`?

**Comment by doom369** [comment]
> Can reporting_raw_data table record string, like Thu Dec 14 12:46:07 2017?

No. This table is just for numbers.

**Comment by bestpika** [comment]
So, if I use `Blynk.virtualWrite()` send string can cause this table empty?

**Comment by doom369** [comment]
@bestpika correct. If those string couldn't be parsed as the number.

**Comment by bestpika** [comment]
Any pin send string (other pin send number) cause this table empty, too?

**Comment by bestpika** [comment]
...I update 0.29.1, then this table have data.
