### ISSUE TITLE
DeviceTiles provisioning new command

### ISSUE THREAD

**Issue by alexkipar** [blynkkk/blynk-server#844]
We need a custom command to create a tempory token without the device, that could be provisioned to a hardware, and only after that to create a device.

**Comment by doom369** [comment]
@alexkipar please describe flow step-by-step. Currently, the server requires the device for the token to be created.

**Comment by alexkipar** [comment]
@doom369 the problem with current provisioning is the next one: we could create device to provision the token to the hardware only before the provisioning would start, but then in the case of an error we would need to remove the device, that could lead to possible issues with drop of internet connection when the device would not be removed and left in the project

**Comment by doom369** [comment]
Roger that.
