### ISSUE TITLE
Make it possible to delete single tabs

### ISSUE THREAD

**Issue by BudBundi** [blynkkk/blynk-server#874]
Please make it possible to delete single tabs, now you must delete the tab widget and create it all new, if you have accidental add a tab to many.

**Comment by doom369** [comment]
@BudBundi you can delete last tab by swiping left tab in widget settings.

**Comment by BudBundi** [comment]
That was not so obvious. Thank you

**Comment by doom369** [comment]
Agree. However, this is described in docs :).
