### ISSUE TITLE
Can't connect to local server.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#880]
Server: 0.30.0
Port: 9443

1)Launch local server
2)Open app
3)Choose Custom server
4)Enter IP and choose port: 9443
5)Enter login and pass
6)Press "Log In"
AR:
![screenshot_2018-01-24-18-01-56-910_cc blynk 1](https://user-images.githubusercontent.com/16590099/35343925-809ccc60-0134-11e8-8cf4-7116acb2f481.png)

Log:
> 18:22:10.604 DEBUG- Using SLF4J as the default logging framework
> 18:22:10.709 INFO - Using data dir 'path'
> 18:22:10.731 DEBUG- Platform: Windows
> 18:22:10.733 DEBUG- -Dio.netty.noUnsafe: false
> 18:22:10.734 DEBUG- Java version: 9
> 18:22:10.735 DEBUG- sun.misc.Unsafe.theUnsafe: available
> 18:22:10.736 DEBUG- sun.misc.Unsafe.copyMemory: available
> 18:22:10.736 DEBUG- java.nio.Buffer.address: available
> 18:22:10.737 DEBUG- direct buffer constructor: available
> 18:22:10.738 DEBUG- java.nio.Bits.unaligned: available, true
> 18:22:10.739 DEBUG- jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
> java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[?:?]
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:262) ~[?:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[?:?]
> 	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:310) ~[server-0.30.0-java8.jar:?]
> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
> 	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:303) ~[server-0.30.0-java8.jar:?]
> 	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208) ~[server-0.30.0-java8.jar:?]
> 	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79) ~[server-0.30.0-java8.jar:?]
> 	at io.netty.util.ConstantPool.<init>(ConstantPool.java:32) ~[server-0.30.0-java8.jar:?]
> 	at io.netty.util.AttributeKey$1.<init>(AttributeKey.java:27) ~[server-0.30.0-java8.jar:?]
> 	at io.netty.util.AttributeKey.<clinit>(AttributeKey.java:27) ~[server-0.30.0-java8.jar:?]
> 	at cc.blynk.server.core.dao.SessionDao.<clinit>(SessionDao.java:28) ~[server-0.30.0-java8.jar:?]
> 	at cc.blynk.server.Holder.<init>(Holder.java:90) ~[server-0.30.0-java8.jar:?]
> 	at cc.blynk.server.launcher.ServerLauncher.start(ServerLauncher.java:119) ~[server-0.30.0-java8.jar:?]
> 	at cc.blynk.server.launcher.ServerLauncher.main(ServerLauncher.java:99) ~[server-0.30.0-java8.jar:?]
> 18:22:10.743 DEBUG- java.nio.DirectByteBuffer.<init>(long, int): available
> 18:22:10.747 DEBUG- sun.misc.Unsafe: available
> 18:22:10.747 DEBUG- -Dio.netty.tmpdir: C:\Users\Dom\AppData\Local\Temp (java.io.tmpdir)
> 18:22:10.747 DEBUG- -Dio.netty.bitMode: 32 (sun.arch.data.model)
> 18:22:10.748 DEBUG- -Dio.netty.noPreferDirect: false
> 18:22:10.749 DEBUG- -Dio.netty.maxDirectMemory: 1037959168 bytes
> 18:22:10.749 DEBUG- -Dio.netty.uninitializedArrayAllocationThreshold: -1
> 18:22:10.753 DEBUG- java.nio.ByteBuffer.cleaner(): unavailable
> java.lang.NoSuchMethodException: sun.misc.Unsafe.invokeCleaner(java.nio.ByteBuffer)
> 	at java.lang.Class.getDeclaredMethod(Class.java:2140) ~[?:?]
> 	at io.netty.util.internal.CleanerJava9.<clinit>(CleanerJava9.java:41) ~[server-0.30.0-java8.jar:?]
> 	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:186) ~[server-0.30.0-java8.jar:?]
> 	at io.netty.util.ConstantPool.<init>(ConstantPool.java:32) ~[server-0.30.0-java8.jar:?]
> 	at io.netty.util.AttributeKey$1.<init>(AttributeKey.java:27) ~[server-0.30.0-java8.jar:?]
> 	at io.netty.util.AttributeKey.<clinit>(AttributeKey.java:27) ~[server-0.30.0-java8.jar:?]
> 	at cc.blynk.server.core.dao.SessionDao.<clinit>(SessionDao.java:28) ~[server-0.30.0-java8.jar:?]
> 	at cc.blynk.server.Holder.<init>(Holder.java:90) ~[server-0.30.0-java8.jar:?]
> 	at cc.blynk.server.launcher.ServerLauncher.start(ServerLauncher.java:119) ~[server-0.30.0-java8.jar:?]
> 	at cc.blynk.server.launcher.ServerLauncher.main(ServerLauncher.java:99) ~[server-0.30.0-java8.jar:?]
> 18:22:10.756 DEBUG- Starting reading user DB.
> 18:22:12.337 DEBUG- Reading user DB finished.
> 18:22:12.337 INFO - Region : local. Host : 192.168.113.2.
> 18:22:12.397 DEBUG- -Dio.netty.eventLoopThreads: 4
> 18:22:12.454 DEBUG- -Dio.netty.noKeySetOptimization: false
> 18:22:12.454 DEBUG- -Dio.netty.selectorAutoRebuildThreshold: 512
> 18:22:12.463 DEBUG- org.jctools-core.MpscChunkedArrayQueue: available
> 18:22:12.618 DEBUG- -Dio.netty.leakDetection.level: disabled
> 18:22:12.618 DEBUG- -Dio.netty.leakDetection.targetRecords: 4
> 18:22:12.621 DEBUG- Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@1b9aa43
> 18:22:13.070 DEBUG- Default protocols (JDK): [TLSv1.2, TLSv1.1, TLSv1] 
> 18:22:13.071 DEBUG- Default cipher suites (JDK): [TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA]
> 18:22:13.105 DEBUG- -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
> 18:22:13.105 DEBUG- -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
> 18:22:13.117 DEBUG- -Dio.netty.allocator.numHeapArenas: 4
> 18:22:13.117 DEBUG- -Dio.netty.allocator.numDirectArenas: 4
> 18:22:13.117 DEBUG- -Dio.netty.allocator.pageSize: 8192
> 18:22:13.119 DEBUG- -Dio.netty.allocator.maxOrder: 11
> 18:22:13.119 DEBUG- -Dio.netty.allocator.chunkSize: 16777216
> 18:22:13.119 DEBUG- -Dio.netty.allocator.tinyCacheSize: 512
> 18:22:13.119 DEBUG- -Dio.netty.allocator.smallCacheSize: 256
> 18:22:13.119 DEBUG- -Dio.netty.allocator.normalCacheSize: 64
> 18:22:13.119 DEBUG- -Dio.netty.allocator.maxCachedBufferCapacity: 32768
> 18:22:13.119 DEBUG- -Dio.netty.allocator.cacheTrimInterval: 8192
> 18:22:13.119 DEBUG- -Dio.netty.allocator.useCacheForAllThreads: true
> 18:22:13.128 DEBUG- -Dio.netty.allocator.type: pooled
> 18:22:13.128 DEBUG- -Dio.netty.threadLocalDirectBufferSize: 65536
> 18:22:13.128 DEBUG- -Dio.netty.maxThreadLocalCharBufferSize: 16384
> 18:22:13.212 INFO - Initializing gmail smtp mail transport. Username : example@gmail.com. SMTP host : smtp.gmail.com:587
> 18:22:13.314 INFO - Didn't find custom user certificates.
> 18:22:13.315 INFO - Didn't find Let's Encrypt certificates.
> 18:22:13.315 WARN - You didn't specified 'server.host' or 'contact.email' properties in server.properties file. Automatic certificate generation is turned off. Please specify above properties for automatic certificates retrieval.
> 18:22:13.315 WARN - ATTENTION. Server certificate paths (cert : 'C:\Users\Dom\Desktop\242', key : 'C:\Users\Dom\Desktop\242') not valid. Using embedded server certs and one way ssl. This is not secure. Please replace it with your own certs.
> 18:22:13.529 DEBUG- -Dio.netty.buffer.bytebuf.checkAccessible: true
> 18:22:13.529 DEBUG- Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@1208b45
> 18:22:13.589 DEBUG- hard.socket.idle.timeout = 15
> 18:22:13.595 DEBUG- app.socket.idle.timeout = 600
> 18:22:13.866 DEBUG- hard.socket.idle.timeout = 15
> 18:22:13.878 DEBUG- -Dio.netty.processId: 684 (auto-detected)
> 18:22:13.881 DEBUG- -Djava.net.preferIPv4Stack: false
> 18:22:13.881 DEBUG- -Djava.net.preferIPv6Addresses: false
> 18:22:13.960 DEBUG- Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
> 18:22:13.961 DEBUG- Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
> 18:22:14.052 DEBUG- -Dio.netty.machineId: 00:1d:60:ff:fe:59:ab:79 (auto-detected)
> 18:22:14.099 INFO - Hardware plain tcp/ip server listening at 8442 port.
> 18:22:14.100 INFO - Hardware SSL server listening at 8441 port.
> 18:22:14.101 INFO - Application server listening at 8443 port.
> 18:22:14.102 INFO - HTTP API and WebSockets server listening at 8080 port.
> 18:22:14.102 INFO - HTTPS API, WebSockets and Admin page server listening at 9443 port.
> 18:22:14.103 INFO - Mqtt hardware server listening at 8440 port.
>

**Comment by Gun-neR** [comment]
Wow... next time can you post the whole error, not just a snippet ;P

Anyhow this is a question more for the Blynk community forum community.blynk.cc

And you are trying to use port 9443 **before** the new App that requires it is even released.  Go back to 8443 and try again... then re read the announcement and await the New App.

**Comment by doom369** [comment]
@Gun-neR issue was with wrong IP during connection.
