### ISSUE TITLE
Error: unable to access jarfile server-0.30.1.jar 

### ISSUE THREAD

**Issue by Quantaindew** [blynkkk/blynk-server#883]
after typing in the command in cmd on windows i get a error message, i have no idea what to do now

![untitled](https://user-images.githubusercontent.com/35188255/35431244-bb2b483e-02a1-11e8-964c-0b89645054f4.png)

**Comment by doom369** [comment]
@Quantaindew you are using wrong jar name.

**Comment by Quantaindew** [comment]
i understood what you meant by saying i wrote the wrong jar file name, but i didn't understand by what you meant by saying that i need to use -java8, can  you highlight the area where I should make the change

**Comment by doom369** [comment]
@Quantaindew checkout https://github.com/blynkkk/blynk-server/releases/tag/v0.30.1. You need to take file ending with `-java8`
