### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by Quantaindew** [blynkkk/blynk-server#885]
when i run the command it says 'Error: Unable to access jarfile'

![2](https://user-images.githubusercontent.com/35188255/35435663-960d52bc-02b1-11e8-8c88-4d44144ab9b1.png)

![3](https://user-images.githubusercontent.com/35188255/35435688-ab591124-02b1-11e8-98f6-b7f95f4b09b3.png)

**Comment by doom369** [comment]
@Quantaindew you need to specify full path to jar file or execute command from folder where jar file is located.
