### ISSUE TITLE
how to connect arduino via usb to blynk local server 

### ISSUE THREAD

**Issue by Quantaindew** [blynkkk/blynk-server#889]
I successfully started the server and the app has been connected to it now how do i connect my arduino via usb, do I have to make changes to blynk ser.bat file ?

![image](https://user-images.githubusercontent.com/35188255/35479779-59e4be86-0425-11e8-911a-fa76a2d1f0a0.png)
 
I have connect the arduino to com 3 and i also changed the comm port to com3
I am stuck i don't know what to change next, I don't know how to identify the server port

![image](https://user-images.githubusercontent.com/35188255/35479805-1b28b2fa-0426-11e8-8962-506cf50687ff.png)

Sorry for my inconvenience I am a dumbass

**Comment by doom369** [comment]
Here is manual - http://help.blynk.cc/how-to-connect-different-hardware-with-blynk/arduino/usb-serial
Please use https://community.blynk.cc/ for technical questions.
