### ISSUE TITLE
Error generating certificates 

### ISSUE THREAD

**Issue by Quantaindew** [blynkkk/blynk-server#901]
This is what i did and this is the output

![image](https://user-images.githubusercontent.com/35188255/35809358-5a7d69ee-0aae-11e8-8867-2d22b27a82ef.png)

how to fix it 

Waiting for your reply

**Comment by doom369** [comment]
Have you read https://github.com/blynkkk/blynk-server#automatic-lets-encrypt-certificates-generation?

**Comment by Quantaindew** [comment]
yes I have i have made the exact same changes in the server.properties file, here is the code :

> Note: MyEmail Id is just used as variable for my real email id which i don't want to share


```
#used for reset password page and certificate generation.
#by default current server IP is taken. could be replaced with more friendly hostname.
#it is recommended to override this property with your server IP to avoid possible problems of host resolving
server.host=smome.blynk.cc

product.name=Smome

#email used for certificate registration, could be omitted in case you already specified it in mail.properties
contact.email=MyEmailID@gmail.com
```

**Comment by doom369** [comment]
Did you make port forwarding?

**Comment by Quantaindew** [comment]
No

**Comment by Quantaindew** [comment]
Is this normal ?

**Comment by doom369** [comment]
In that case - please follow instructions in the above link. For further technical questions please use https://community.blynk.cc/
