### ISSUE TITLE
Add iconName field for Template and Device

### ISSUE THREAD

**Issue by eepetrash** [blynkkk/blynk-server#902]
We can now assign hardcoded icon in Templates settings. In the exported apps, users can also change the icon during device provisioning.

Type: String.

**Comment by doom369** [comment]
@FYI @alexkipar

**Comment by alexkipar** [comment]
@doom369 what about String templateId  ?

**Comment by alexkipar** [comment]
@doom369 or it would be generated from the id field?

**Comment by doom369** [comment]
@alexkipar it was added before.
