### ISSUE TITLE
After registration no confirmation e-mail

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#924]
1)Register a new user(qa)
2)Open email
AR:
No message

**Comment by Refenz** [comment]
@doom369 
Yes.

**Comment by Refenz** [comment]
@doom369 
Update:
The letter came, but with a long delay (40-60 minutes).
This is normal?

**Comment by doom369** [comment]
Not normal. Probably mail provider issue. This may happens sometimes.

**Comment by Refenz** [comment]
@doom369 
Another e-mail:
1)Create new e-mail account (14:49)
2)Create new Blynk account (14:50)
3)Create new project and send All tokens(14:51)
4)Send a request to reset password(14:52)
AR:
Delay: 3.5 - 5 hours
- received a token after the project was created(18:32)
- received a message of successful registration(18:49)
- received a message to reset the password(20:32)
- received a message with all project tokens(20:51)
![hm](https://user-images.githubusercontent.com/16590099/36754132-db5642c0-1c10-11e8-8c15-73107f784bf0.PNG)
P.S. Close if won't fix or look for a reason

**Comment by doom369** [comment]
@Refenz just checked on QA. Mails come instantly. Probably issue is with your mail provider.
