### ISSUE TITLE
Admin UI: remove all mentionings of "dash", "dashboard". Change to "Project"

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-server#93]

**Comment by doom369** [comment]
@blynkkk this is not possible without affecting applications and requires many refactorings.

**Comment by blynkkk** [comment]
it doesn't mean that it's closed

**Comment by doom369** [comment]
@blynkkk it will take many man-days with 0 profit. so no reason to hold it open.

**Comment by blynkkk** [comment]
Please don't use these terms in future. It creates a lot of confusion.

**Comment by doom369** [comment]
@blynkkk I don't. But this code is from first days.
