### ISSUE TITLE
Data will be automatically deleted in the DB

### ISSUE THREAD

**Issue by hznupeter** [blynkkk/blynk-server#934]
version:0.32.2-java8
i install blynk server and postgresql on my Pi, and i did everything as the guide.
but i met a strange question.
i check the data on the table 'Reporting Average Minute',after i set up the app,there are 360 lines ,but ,several hours later,there only left about 100, the second day ,on 20 left.
why the data on the  table 'Reporting Average Minute' will lost?

**Comment by doom369** [comment]
You need to set 

`clean.reporting=false` in `db.properties` file.

This is data used mostly for analytics you average user don't need it.

**Comment by doom369** [comment]
@hznupeter please read carefully my answer again. You need to change `db.properties` and not `server.properties`.

**Comment by kylechen1980** [comment]
Hi:
So if I want to keep all of the minute records, 
the only thing I need is a file named db.properties containing only a clause "clean.reporting=false" in it
and put this file in the same folder as server.properties, is that correct?

Or I have to deal with other db properties?
