### ISSUE TITLE
Handle situations when the device's TurnOff/DeepSleep has been programmed.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-server#937]
For example, before turning off, the device sends a command to the server.
The server handles the situation that the device will be turned off.
After disconnecting the device, the server does not send notifications/emails.

This will be convenient for users who disconnect their devices to save battery, but do not want to receive notifications every time.

**Comment by doom369** [comment]
@Refenz we already implemented this via notifications widget - http://docs.blynk.cc/#widgets-notifications-push-notifications

Maybe this should also be in project settings. But this is up to Pavel to decide.
