### ISSUE TITLE
Add 'maximumFractionDigits' field to Slider

### ISSUE THREAD

**Issue by eepetrash** [blynkkk/blynk-server#939]
Widgets: Slider, VerticalSlider
New field: int maximumFractionDigits

An integer field indicating the maximum number of digits after the decimal separator allowed in a value.
The default value: 0
If the field is absent (old widgets) we can treat _maximumFractionDigits_ as zero to behave as integer

**Comment by pieman64** [comment]
@eepetrash and @doom369 why not default value of zero digits rather than 2 as I'm guessing more users will want no digits?

**Comment by doom369** [comment]
@pieman64 already fixed.

**Comment by pieman64** [comment]
@doom369 I mean zero digits for all future additions of the slider not just exisiting sliders being used. This is not what @eepetrash suggests in his post.

**Comment by doom369** [comment]
Yes. I edited above post. So default is 0.

**Comment by doom369** [comment]
deployed to QA
