### ISSUE TITLE
Move webhook failure limit to properties file

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-server#941]

**Comment by pieman64** [comment]
@doom369 have you seen the emails I sent to Roman regarding a webhook fail for our app?
Me and and another user had a webhook failure around 60 hours ago with 500 and 502 errors. Maybe 3rd party server was down but they indicate no problems at their side. I have turned off my system to see if your system will unlock the webhook block. How long does the block last?

**Comment by doom369** [comment]
Yes. I saw it. Block is permanent. I can for now just increase limit of failure to larger number (10 currently)

**Comment by pieman64** [comment]
Block is permanent?

**Comment by pieman64** [comment]
The 3rd party server is pretty reliable but like all servers they go down at some point.
As we have a 10 or 15s frequency it doesn't need to be down long to rack up 10 or even 100 failures.
Can't it have a time block?

**Comment by doom369** [comment]
@pieman64 oh, this is actually was already implemented. I increased limit for your server.

**Comment by pieman64** [comment]
All working fine now, thanks.
