### ISSUE TITLE
Push notification doesn't work on master app

### ISSUE THREAD

**Issue by yonas124** [blynkkk/blynk-server#992]
I invoked notify using RESTFUL API but only shared apps showed notification.
It doesn't show up on the master app on my phone.

The notification on the shared apps also pop up only when master app is opened/active.

Is this normal?

**Comment by doom369** [comment]
Please try to set priority to "High" within notifications widget. For further questions please use https://community.blynk.cc/

**Comment by yonas124** [comment]
I did set to high. Still no notification.
Is it the Android version? Mine is android 7.0 with Blynk 2.20.1

**Comment by yonas124** [comment]
It showed up on my two friends phone so my step is correct. Only mine didn't (master app). And I have allowed all notification permission for Blynkk on android system settling.

This is confusing @_@

**Comment by doom369** [comment]
@yonas124 probably you have specific setting for push notificaitons within your phone. You need to check that.

**Comment by yonas124** [comment]
Well I already enabled all permissions, so I guess there must be something wrong with my phone.

Anyway, consider this issue closed.

**Comment by Refenz** [comment]
@yonas124 
1. Notifications came earlier?
If so, when did they stop?
2. Try creating a new account and sending the notification to the new project.
3. Does the new project receive these notifications (without activated sharing)?

**Comment by yonas124** [comment]
Notification shows up on different phones who have shared copy of the project. But it never shows up on my phone.

 

I tried to send notification on new project without activated sharing and it shows up!!

I wonder if it’s a bug or it’s just how it works with sharing enabled.

**Comment by Refenz** [comment]
@yonas124 
Try asking this question here: https://community.blynk.cc
